"""Connect Wizard — one-liner customer onboarding.

Flow:
  1. Authenticated customer hits POST /connect-wizard/issue-token
     → backend signs a JWT (15-min TTL) with their tenant_id
  2. Customer's browser polls GET /connect-wizard/status/{token}
  3. Customer runs the one-liner script on their Windows server. The
     script is served by GET /connect-wizard/win/{token} (returns
     PowerShell that does setup + POSTs handshake back).
  4. The script's last step POSTs to /connect-wizard/handshake which
     creates an IntegrationConnection row for the tenant.
  5. Browser poll picks up "ready" status and redirects to dashboard.

Security:
  - Token is signed with SESSION_SECRET, includes tenant_id + nonce + exp.
  - Handshake includes one-time agent password generated by the script
    (random per machine, never echoed back to the customer).
  - Connection rows are stored with credentials encrypted via Fernet
    (existing per-tenant encryption used elsewhere in the platform).
"""
from __future__ import annotations

import logging
import os
import secrets
import time

logger = logging.getLogger(__name__)
from datetime import datetime
from typing import Optional

import jwt
from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel
from sqlalchemy import func
from sqlalchemy.orm import Session

from grc.crypto import encrypt_secret
from grc.models import IntegrationConnection, get_db, ITAsset
from grc.routers.auth_router import get_user_primary_tenant, require_auth, GRCUser

router = APIRouter(prefix="/connect-wizard", tags=["Connect Wizard"])

SESSION_SECRET = os.environ.get("SESSION_SECRET", "dev-secret")
TOKEN_TTL_SECONDS = 60 * 60  # 60 minutes — gives operators headroom for
                              # first-time WinRM/SSH setup on the target before
                              # the handshake fires. Was 15 min, which expired
                              # mid-config for anyone reading the docs while
                              # configuring the target's auth/firewall/cert.

# Hints rendered to the operator in the wizard UI when pre-flight rejects
# their credentials. Keep these in one place so we don't drift between
# the API and the React error banner.
_PREFLIGHT_HINTS = {
    "auth_failed": (
        "The username or password is wrong. For Windows: confirm the service "
        "account exists, is NOT locked, and that you typed the exact password "
        "set on the local account (Set-LocalUser as Admin if you reset it). "
        "For Linux: confirm the user can `ssh user@host` from a terminal first. "
        "For AWS: re-paste the access key + secret from the IAM console."
    ),
    "network_unreachable": (
        "The scanner cannot reach the target. For Windows: run "
        "`Test-NetConnection <host> -Port 5986` from this server. For Linux: "
        "run `nc -zv <host> 22`. Check firewall + that the service is running."
    ),
    "ssl_error": (
        "TLS handshake failed. The wizard auto-trusts self-signed certs, so "
        "this usually means the WinRM listener is HTTP-only (port 5985), not "
        "HTTPS (5986). Re-run the wizard installer to set up the HTTPS listener "
        "or switch the connection to HTTP."
    ),
    "config_error": (
        "A required field was missing or the runtime is misconfigured. "
        "Check that hostname, username, and password are all filled in."
    ),
    "unknown": (
        "Something went wrong during pre-flight. Check the server logs and "
        "verify the target host is reachable + the service account works."
    ),
}


# ─── Models ──────────────────────────────────────────────────────────────────

class IssueTokenIn(BaseModel):
    platform: str  # "windows" | "linux" | "aws"


class HandshakeIn(BaseModel):
    tenant_token: str
    hostname: str
    display_label: Optional[str] = None   # operator-friendly name for the UI
    os_name: Optional[str] = None
    winrm_endpoint: Optional[str] = None
    ssh_endpoint: Optional[str] = None
    service_account: Optional[str] = None
    agent_password: Optional[str] = None
    cert_fingerprint: Optional[str] = None
    # CIS Module Updated — when the operator clicks "Connect" on an
    # asset row in /assets, the wizard URL carries `?asset_id=N`. We
    # forward it here so the backend can bind the new connection
    # DIRECTLY to that asset row, instead of relying on the host_name
    # fallback match (which breaks when the operator types IP vs FQDN).
    asset_id: Optional[int] = None
    # ─── Extended platforms (banks: MSSQL/Postgres/MySQL/AD/Azure/K8s) ──
    # Optional, only present when the operator picks one of the new
    # platforms in the Connect Wizard. The handshake handler reads only
    # the fields relevant to the chosen platform.
    database_name: Optional[str] = None          # SQL DBs (mssql/postgres/mysql)
    db_port: Optional[int] = None                # SQL DBs (overrides default 1433/5432/3306)
    # Oracle uses TNS service name OR SID instead of a generic database name.
    # The runner accepts either — service_name preferred; SID is the legacy
    # form on older installs (Oracle 11g and earlier defaults like ORCL/XE).
    oracle_service_name: Optional[str] = None    # Oracle (preferred over SID)
    oracle_sid: Optional[str] = None             # Oracle (alternative to service_name)
    ldap_bind_dn: Optional[str] = None           # AD/LDAP bind DN
    ldap_use_ssl: Optional[bool] = None          # AD/LDAP — true for ldaps:// (port 636)
    azure_subscription_id: Optional[str] = None  # Azure
    azure_tenant_id: Optional[str] = None        # Azure
    azure_client_id: Optional[str] = None        # Azure
    azure_client_secret: Optional[str] = None    # Azure
    kubeconfig: Optional[str] = None             # Kubernetes (YAML blob)
    k8s_server: Optional[str] = None             # Kubernetes (alt: server+token+ca)
    k8s_token: Optional[str] = None              # Kubernetes
    k8s_ca_cert: Optional[str] = None            # Kubernetes


# In-memory status store. Production would use Redis; for v1 this is fine
# because tokens are short-lived and a process restart only invalidates
# the wizard session (customer just clicks "Connect" again).
_STATUS: dict[str, dict] = {}


def _sign(payload: dict) -> str:
    return jwt.encode(payload, SESSION_SECRET, algorithm="HS256")


def _verify(token: str) -> dict:
    try:
        return jwt.decode(token, SESSION_SECRET, algorithms=["HS256"])
    except jwt.PyJWTError as e:
        raise HTTPException(401, f"Invalid token: {e}")


# ─── Endpoints ───────────────────────────────────────────────────────────────

@router.post("/issue-token")
def issue_token(
    body: IssueTokenIn,
    db: Session = Depends(get_db),
    current_user: GRCUser = Depends(require_auth),
):
    """Issue a short-lived signed token for the wizard handshake.

    Frontend calls this when the customer picks a platform in the wizard.
    The token gets embedded in the one-liner script URL.
    """
    # cisco + oracle added so the agentless quick-start covers network
    # devices and DB targets, not just OS hosts. The /handshake endpoint
    # already handles ssh_endpoint + sql_endpoint fields, so the only
    # backend gate that needed widening was this validator.
    # Banking-relevant additions: mssql/postgres/mysql DBs, AD/LDAP, Azure
    # cloud, Kubernetes. Each one has a registered runner; the handshake
    # path stores the supplied credentials in an IntegrationConnection and
    # the credentials.py picker dispatches by integration_type.
    _allowed_platforms = {
        "windows", "linux", "aws", "digitalocean", "cisco", "oracle",
        "mssql", "postgres", "mysql", "ad", "azure", "k8s",
    }
    if body.platform not in _allowed_platforms:
        raise HTTPException(
            422,
            f"platform must be one of: {', '.join(sorted(_allowed_platforms))}",
        )
    tenant_id = get_user_primary_tenant(current_user, db)
    nonce = secrets.token_urlsafe(16)
    now = int(time.time())
    payload = {
        "tenant_id": tenant_id,
        "user_id": current_user.id,
        "platform": body.platform,
        "nonce": nonce,
        "iat": now,
        "exp": now + TOKEN_TTL_SECONDS,
    }
    token = _sign(payload)
    _STATUS[nonce] = {"state": "pending", "platform": body.platform, "tenant_id": tenant_id}
    return {
        "token": token,
        "nonce": nonce,
        "expires_in": TOKEN_TTL_SECONDS,
        "script_url": f"/grc/connect-wizard/{body.platform}/{token}",
    }


@router.get("/status/{nonce}")
def get_status(
    nonce: str,
    current_user: GRCUser = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Frontend polls this every ~3s while showing the one-liner. When the
    customer's machine POSTs to /handshake, this flips to ready."""
    rec = _STATUS.get(nonce)
    if not rec:
        raise HTTPException(404, "Unknown nonce or token expired")
    # Tenant scope check
    tenant_id = get_user_primary_tenant(current_user, db)
    if rec.get("tenant_id") != tenant_id:
        raise HTTPException(403, "Cross-tenant nonce access forbidden")
    return rec


@router.get("/windows/{token}", response_class=PlainTextResponse)
def windows_script(token: str):
    """Return the PowerShell one-liner installer with the tenant token baked in.

    Customer runs as Administrator. Script enables WinRM, creates a read-only
    PER-TENANT service account named ``complivrs_t{tenant_id}`` so two tenants
    connecting to the same machine cannot clobber each other's credentials.

    NOTE: served as text/plain so `iwr ... | iex` works in PowerShell.
    """
    payload = _verify(token)
    if payload.get("platform") != "windows":
        raise HTTPException(400, "Token is not for windows platform")
    handshake_url = "http://localhost:5000/grc/connect-wizard/handshake"
    return _build_windows_script(token, handshake_url, payload["tenant_id"])


@router.get("/linux/{token}", response_class=PlainTextResponse)
def linux_script(token: str):
    payload = _verify(token)
    if payload.get("platform") != "linux":
        raise HTTPException(400, "Token is not for linux platform")
    handshake_url = "http://localhost:5000/grc/connect-wizard/handshake"
    return _build_linux_script(token, handshake_url, payload["tenant_id"])


@router.post("/handshake")
def handshake(body: HandshakeIn, db: Session = Depends(get_db)):
    """Called by the customer's machine at the end of the install script.

    NOT authenticated by user session — authenticated by the signed JWT
    embedded in the script (only the customer who started the wizard could
    have received it).
    """
    try:
        return _handshake_inner(body, db)
    except HTTPException as exc:
        # CIS-merge debug shim — log the full preflight detail to the
        # server console so the operator doesn't have to open DevTools
        # to see WHY the 400 fired. Keeps the response shape identical
        # (Starlette still serialises `exc.detail` as the body) so the
        # frontend's existing handler isn't affected.
        if exc.status_code == 400 and isinstance(exc.detail, dict):
            logger.warning(
                "connect-wizard handshake 400 — code=%s stage=%s message=%s",
                exc.detail.get("code"),
                exc.detail.get("stage"),
                exc.detail.get("message"),
            )
            checks = exc.detail.get("checks_run") or []
            for line in checks:
                logger.warning("  · check: %s", line)
        raise


def _handshake_inner(body: "HandshakeIn", db: Session) -> dict:
    payload = _verify(body.tenant_token)
    tenant_id = payload["tenant_id"]
    user_id = payload.get("user_id")
    nonce = payload["nonce"]
    platform = payload["platform"]

    # Defensive: strip any leading/trailing whitespace, tabs, and CR/LF from
    # operator-supplied strings. The Manual Credentials form is a common
    # source of accidental trailing tabs/newlines (tabbing between fields,
    # paste from a CSV cell, etc.) which Windows/Linux auth then rejects as
    # invalid credentials — a confusing failure mode for non-technical
    # operators who can SEE the values are "correct".
    def _clean(s: str | None) -> str | None:
        if s is None:
            return None
        # Strip leading/trailing whitespace + remove any embedded NBSP / tabs / newlines
        cleaned = s.strip().replace("\t", "").replace("\r", "").replace("\n", "")
        return cleaned or None

    body.hostname = _clean(body.hostname) or body.hostname
    body.display_label = _clean(body.display_label)
    body.service_account = _clean(body.service_account)
    body.agent_password = _clean(body.agent_password)
    body.winrm_endpoint = _clean(body.winrm_endpoint)
    body.ssh_endpoint = _clean(body.ssh_endpoint)

    # Build connection name — prefer operator-provided label, fall back to host.
    label = (body.display_label or body.hostname).strip()
    conn_name = f"{platform.capitalize()} — {label}"
    integration_type = {
        "windows": "windows_winrm",
        "linux": "linux_ssh",
        "aws": "aws_readonly",
        "digitalocean": "linux_ssh",
        "cisco": "netdev_ssh",
        "oracle": "oracle_sql",
        "mssql": "mssql_sql",
        "postgres": "postgres_sql",
        "mysql": "mysql_sql",
        "ad": "ldap_query",
        "azure": "azure_readonly",
        "k8s": "k8s_api",
    }[platform]
    console_url = body.hostname

    # Default port per platform — Windows WinRM 5986, Linux/DO SSH 22, AWS HTTPS 443.
    # If the operator gave us a custom port in the *_endpoint URL we honour that
    # instead, so the form's "Port" field actually means something. Without this,
    # any non-default port (jump host, lab on 2222, hardened Cisco on 2022, etc.)
    # silently reverted to the platform default and pre-flight would fail with
    # the wrong reason ("Cannot reach <host>:22" even when the operator typed 2222).
    if platform == "windows":
        console_port = 5986
    elif platform == "aws" or platform == "azure":
        console_port = 443
    elif platform == "mssql":
        console_port = body.db_port or 1433
    elif platform == "postgres":
        console_port = body.db_port or 5432
    elif platform == "mysql":
        console_port = body.db_port or 3306
    elif platform == "ad":
        console_port = 636 if body.ldap_use_ssl else 389
    elif platform == "k8s":
        console_port = 443  # k8s API
    else:  # linux, digitalocean, cisco, oracle
        console_port = 22 if platform != "oracle" else 1521

    def _extract_port(endpoint: Optional[str], fallback: int) -> int:
        if not endpoint:
            return fallback
        # Forms: ssh://host:2222, oracle://host:1521/orcl, https://host:5986/wsman
        try:
            from urllib.parse import urlparse
            p = urlparse(endpoint)
            if p.port:
                return int(p.port)
        except Exception:
            pass
        return fallback

    if platform == "windows":
        console_port = _extract_port(body.winrm_endpoint, console_port)
    elif platform == "aws":
        pass  # AWS has no port in this flow
    else:
        console_port = _extract_port(body.ssh_endpoint, console_port)
    prefix = f"WIZARD_{nonce.upper().replace('-','')[:10]}"

    # ──────────────────────────────────────────────────────────────────
    # LIVE PRE-FLIGHT
    #
    # Before we persist anything, prove the supplied credentials actually
    # work against the target host. This catches:
    #   • wrong password typed in manual creds form
    #   • account locked / disabled on Windows
    #   • WinRM service not running / firewall blocking port 5986
    #   • SSH not running / wrong port
    #   • AWS access key disabled or has wrong region
    #
    # Without this check, bad creds get stored, the wizard reports
    # "connected", and every scheduled scan silently fails with auth
    # errors — exactly the issue we hit on the first attempt today.
    # ──────────────────────────────────────────────────────────────────
    from grc.modules.compliance_plugins.services.preflight import preflight_check

    # ─── Skip preflight for the new banking platforms ─────────────────
    # MSSQL/Postgres/MySQL/AD/Azure/K8s have rich, structured credentials
    # that the preflight_check helper doesn't yet know how to test. Rather
    # than block the connect flow, we trust the operator-provided creds
    # and let the runner surface a clear error on first scan. Once we
    # write per-platform `preflight_*` probes, we can re-enable here.
    if platform in ("mssql", "postgres", "mysql", "ad", "azure", "k8s"):
        # Skip preflight; just proceed to persistence.
        pass
    # ─── Universal TCP probe helper ───────────────────────────────
    # Used by all platforms to test reachability before paying for a
    # full protocol handshake. Fast — 2s timeout.
    import socket as _sock
    def _tcp_open(host: str, port: int, timeout: float = 2.0) -> bool:
        try:
            with _sock.create_connection((host, port), timeout=timeout):
                return True
        except Exception:
            return False

    if platform == "windows":
        # ─── WinRM auto-probe with diagnostic ─────────────────────────
        # We distinguish FOUR failure modes and surface a specific cause +
        # copy-paste fix command for each, instead of a generic "check
        # firewall and WinRM service" hint.
        explicit_port = _extract_port(body.winrm_endpoint, 0)
        if explicit_port and explicit_port not in (0,):
            scheme = "http" if explicit_port == 5985 else "https"
            probe_candidates = [(explicit_port, scheme)]
        else:
            probe_candidates = [(5986, "https"), (5985, "http")]

        # Stage 1: ICMP ping to distinguish "host gone" vs "host up but
        # ports closed". Both Windows and Linux raw ICMP need privileges
        # so we use the OS ping command instead.
        import subprocess as _sp
        def _ping_alive(host: str) -> bool:
            try:
                if os.name == "nt":
                    out = _sp.run(["ping", "-n", "2", "-w", "1500", host],
                                  capture_output=True, timeout=6)
                else:
                    out = _sp.run(["ping", "-c", "2", "-W", "2", host],
                                  capture_output=True, timeout=6)
                # 0 only when at least one reply was received
                return out.returncode == 0
            except Exception:
                return False

        host_alive = _ping_alive(body.hostname)
        port_results = [(p, s, _tcp_open(body.hostname, p)) for p, s in probe_candidates]
        any_open = next(((p, s) for p, s, ok in port_results if ok), None)

        if not host_alive and not any_open:
            # Host completely unreachable — likely wrong IP / different network
            raise HTTPException(
                status_code=400,
                detail={
                    "preflight_failed": True,
                    "code": "host_unreachable",
                    "stage": "icmp",
                    "message": (
                        f"Host {body.hostname} does not respond to ping AND no WinRM "
                        f"port answered. The IP is likely wrong, the host is offline, "
                        f"or the two of you aren't on the same network."
                    ),
                    "checks_run": [
                        f"ping {body.hostname} — no reply",
                        *[f"TCP {body.hostname}:{p} — refused/timeout" for p, _, ok in port_results if not ok],
                    ],
                    "fix_steps": [
                        {
                            "title": "Verify the IP is correct (target's admin runs this)",
                            "code": "ipconfig | findstr /R \"Wireless Ethernet IPv4\"",
                            "explain": "Pick the IP under the *real* Wi-Fi or Ethernet adapter, NOT vEthernet/Docker/WSL bridges.",
                        },
                        {
                            "title": "Verify you're on the same network (target's admin runs this)",
                            "code": "ipconfig | findstr Gateway",
                            "explain": "Your machine and the target must share a default gateway, OR be on the same Wi-Fi.",
                        },
                    ],
                },
            )

        if host_alive and not any_open:
            # Host reachable but WinRM ports closed — service stopped OR
            # firewall blocks (Public profile is the usual culprit).
            tried = " / ".join(f"{p}" for p, _, _ in port_results)
            raise HTTPException(
                status_code=400,
                detail={
                    "preflight_failed": True,
                    "code": "winrm_ports_closed",
                    "stage": "tcp",
                    "message": (
                        f"Host {body.hostname} responds to ping but BOTH WinRM ports "
                        f"({tried}) are closed. WinRM service is stopped, the firewall "
                        f"blocks it, or the network profile is Public (default-blocks WinRM)."
                    ),
                    "checks_run": [
                        f"ping {body.hostname} — replies received",
                        *[f"TCP {body.hostname}:{p} — closed" for p, _, ok in port_results if not ok],
                    ],
                    "fix_steps": [
                        {
                            "title": "On the target PC — open POWERSHELL as a real Administrator. Win+X menu often gives non-admin even when it says 'Admin'. Best way: Start menu → type 'powershell' → right-click 'Windows PowerShell' → 'Run as administrator' → UAC Yes. The title bar MUST say 'Administrator: Windows PowerShell' — otherwise the cmdlets below will fail with Access Denied.",
                            "code": (
                                "Enable-PSRemoting -SkipNetworkProfileCheck -Force\n"
                                "winrm set winrm/config/service '@{AllowUnencrypted=\"true\"}'\n"
                                "winrm set winrm/config/service/auth '@{Basic=\"true\"}'\n"
                                "Get-Service WinRM"
                            ),
                            "explain": (
                                "Starts the WinRM service, opens 5985/5986 in firewall, lets the demo "
                                "use Basic auth over plain HTTP. The last line should print "
                                "'Status: Running' — that's the success signal."
                            ),
                        },
                        {
                            "title": "Verify the firewall rules (still in Admin PowerShell)",
                            "code": "Get-NetFirewallRule -DisplayName '*WinRM*' | Format-Table DisplayName, Enabled",
                            "explain": "At least one WinRM-In rule must show Enabled: True. If all are False, the previous block didn't actually run as admin — re-open PowerShell with 'Run as administrator'.",
                        },
                    ],
                },
            )

        # One or more ports open — proceed to actual WinRM handshake with
        # the first open port.
        console_port, winrm_scheme = any_open
        test_creds = {
            "winrm_endpoint": f"{winrm_scheme}://{body.hostname}:{console_port}/wsman",
            "winrm_username": body.service_account,
            "winrm_password": body.agent_password,
            "winrm_transport": "ntlm",
            "winrm_server_cert_validation": "ignore",
        }
    elif platform in ("linux", "digitalocean", "cisco"):
        # ─── SSH auto-probe ─────────────────────────────────────────
        # Operator gives only IP. We try the standard SSH port 22 first,
        # then common alternates (2222 for jump hosts / labs, 2022 for
        # hardened Cisco). Explicit port in ssh_endpoint short-circuits.
        explicit_port = _extract_port(body.ssh_endpoint, 0)
        if explicit_port:
            ssh_probe = [explicit_port]
        else:
            ssh_probe = [22, 2222, 2022]
        chosen_ssh: Optional[int] = None
        for p in ssh_probe:
            if _tcp_open(body.hostname, p):
                chosen_ssh = p
                break
        if chosen_ssh is None:
            raise HTTPException(
                status_code=400,
                detail={
                    "preflight_failed": True,
                    "code": "ssh_unreachable",
                    "message": (
                        f"Could not reach {body.hostname} on any common SSH port "
                        f"(tried {', '.join(str(x) for x in ssh_probe)}). Check that "
                        f"SSH is running and a port is open."
                    ),
                    "hint": _PREFLIGHT_HINTS.get("network", "Check firewall and sshd."),
                },
            )
        console_port = chosen_ssh
        test_creds = {
            "ssh_host": body.hostname,
            "ssh_port": console_port,
            "ssh_username": body.service_account,
            "ssh_password": body.agent_password,
        }
    elif platform == "oracle":
        # ─── Oracle TNS auto-probe ──────────────────────────────────
        explicit_port = _extract_port(body.ssh_endpoint, 0)
        if explicit_port:
            ora_probe = [explicit_port]
        else:
            ora_probe = [1521, 1522]
        chosen_ora: Optional[int] = None
        for p in ora_probe:
            if _tcp_open(body.hostname, p):
                chosen_ora = p
                break
        if chosen_ora is None:
            raise HTTPException(
                status_code=400,
                detail={
                    "preflight_failed": True,
                    "code": "oracle_unreachable",
                    "message": (
                        f"Could not reach {body.hostname} on Oracle listener "
                        f"(tried {', '.join(str(x) for x in ora_probe)})."
                    ),
                    "hint": _PREFLIGHT_HINTS.get("network", "Check listener + firewall."),
                },
            )
        console_port = chosen_ora
        test_creds = {
            "ssh_host": body.hostname,
            "ssh_port": console_port,
            "ssh_username": body.service_account,
            "ssh_password": body.agent_password,
        }
    elif platform == "aws":
        # AwsForm packs the access key into `service_account` and the
        # secret key into `agent_password` so the same handshake schema
        # works for all platforms. hostname carries the AWS region label
        # (e.g. "aws-us-east-1" or "Production AWS").
        test_creds = {
            "aws_access_key_id": body.service_account,
            "aws_secret_access_key": body.agent_password,
            "aws_region": (body.os_name or "").replace("AWS Account · ", "").strip() or "us-east-1",
        }
    else:
        test_creds = None

    if test_creds is not None:
        pf = preflight_check(integration_type, test_creds)
        if not pf.ok:
            # Map preflight code → exact-cause fix recipe. Different code
            # families need different fixes (auth vs cert vs network).
            fix_steps_by_code = {
                "auth_failed": [
                    {
                        "title": "Most likely: wrong username/password OR account locked on target",
                        "code": "net user <username>",
                        "explain": "Run on the target PC to confirm the account exists and isn't disabled. Try logging in with the same creds via RDP to verify they work.",
                    },
                    {
                        "title": "If using local account on a non-domain host",
                        "code": "winrm set winrm/config/service '@{AllowUnencrypted=\"true\"}'; winrm set winrm/config/service/auth '@{Basic=\"true\"}'",
                        "explain": "Local accounts require Basic auth over HTTP for WinRM. Domain accounts use NTLM/Kerberos automatically.",
                    },
                ],
                "tls_error": [
                    {
                        "title": "Target's HTTPS WinRM cert isn't trusted by our scanner",
                        "code": "winrm delete winrm/config/Listener?Address=*+Transport=HTTPS; $cert = New-SelfSignedCertificate -DnsName $env:COMPUTERNAME -CertStoreLocation Cert:\\LocalMachine\\My; winrm create winrm/config/Listener?Address=*+Transport=HTTPS \"@{Hostname=$env:COMPUTERNAME;CertificateThumbprint=$cert.Thumbprint}\"",
                        "explain": "Rebuild the HTTPS listener with a fresh self-signed cert. Our scanner has cert_validation=ignore so any cert works.",
                    },
                ],
                "ssh_handshake_failed": [
                    {
                        "title": "SSH server rejected our connection",
                        "code": "systemctl status sshd; tail -20 /var/log/auth.log",
                        "explain": "Run on the target to see why sshd rejected the connection. Common causes: PasswordAuthentication=no, user not in AllowUsers, account locked.",
                    },
                ],
                "network": [
                    {
                        "title": "Verify network path from this server to target",
                        "code": f"Test-NetConnection {body.hostname or '<target>'} -Port <port>",
                        "explain": "If TcpTestSucceeded is False, fix the network/firewall before any creds will work.",
                    },
                ],
            }
            raise HTTPException(
                status_code=400,
                detail={
                    "preflight_failed": True,
                    "code": pf.code,
                    "stage": "protocol",
                    "message": pf.detail,
                    "exact_error": getattr(pf, "raw", None) or pf.detail,
                    "fix_steps": fix_steps_by_code.get(
                        pf.code,
                        [{"title": "Generic fallback", "code": "", "explain": pf.detail}],
                    ),
                    "hint": _PREFLIGHT_HINTS.get(pf.code, "Review credentials and target host configuration."),
                },
            )

    existing = (
        db.query(IntegrationConnection)
        .filter(
            IntegrationConnection.tenant_id == tenant_id,
            IntegrationConnection.connection_name == conn_name,
        )
        .first()
    )
    # ─── Build credentials_extra_json for runners that need richer creds.
    # The runner code in extended_runners.py reads from a dict like:
    #   {"mssql_host": ..., "mssql_username": ..., "mssql_password": ...}
    # We assemble that here using the prefix expected by each runner.
    # Encrypted secret bits (passwords, client secrets, tokens) go through
    # encrypt_secret(); structured public bits (DN, server URLs, subscription
    # IDs) are stored plain so the runners can read them without decryption.
    extra: Optional[dict] = None
    if platform in ("mssql", "postgres", "mysql"):
        prefix_map = {"mssql": "mssql", "postgres": "postgres", "mysql": "mysql"}
        p = prefix_map[platform]
        extra = {
            f"{p}_host": body.hostname,
            f"{p}_port": console_port,
            f"{p}_username": body.service_account,
            f"{p}_password": encrypt_secret(body.agent_password),
            f"{p}_database": body.database_name or None,
        }
    elif platform == "oracle":
        # Oracle runner expects oracle_host/port/username/password and EITHER
        # oracle_service_name OR oracle_sid. Operator may supply either via
        # the form's dedicated fields; we also accept `database_name` as a
        # legacy alias for service_name so existing manual integrations keep
        # working.
        extra = {
            "oracle_host": body.hostname,
            "oracle_port": console_port,
            "oracle_username": body.service_account,
            "oracle_password": encrypt_secret(body.agent_password),
            "oracle_service_name": (
                body.oracle_service_name or body.database_name or None
            ),
            "oracle_sid": body.oracle_sid or None,
        }
    elif platform == "ad":
        extra = {
            "ldap_host": body.hostname,
            "ldap_port": console_port,
            "ldap_use_ssl": bool(body.ldap_use_ssl),
            "ldap_bind_dn": body.ldap_bind_dn or body.service_account,
            "ldap_username": body.service_account,
            "ldap_password": encrypt_secret(body.agent_password),
        }
    elif platform == "azure":
        extra = {
            "azure_subscription_id": body.azure_subscription_id,
            "azure_tenant_id": body.azure_tenant_id,
            "azure_client_id": body.azure_client_id,
            "azure_client_secret": encrypt_secret(body.azure_client_secret or ""),
        }
    elif platform == "k8s":
        if body.kubeconfig:
            extra = {"kubeconfig": encrypt_secret(body.kubeconfig)}
        elif body.k8s_server and body.k8s_token:
            extra = {
                "k8s_server": body.k8s_server,
                "k8s_token": encrypt_secret(body.k8s_token),
                "k8s_ca_cert": body.k8s_ca_cert,
            }

    if existing:
        conn = existing
        conn.console_url = console_url
        conn.console_port = console_port
        conn.username = body.service_account or f"complivrs_t{tenant_id}"
        conn.password = encrypt_secret(body.agent_password) if body.agent_password else conn.password
        if extra is not None:
            conn.credentials_extra_json = extra
        conn.status = "connected"
        conn.is_active = True
    else:
        conn = IntegrationConnection(
            tenant_id=tenant_id,
            integration_type=integration_type,
            connection_name=conn_name,
            console_url=console_url,
            console_port=console_port,
            auth_method="basic",
            credential_env_prefix=prefix,
            username=body.service_account or f"complivrs_t{tenant_id}",
            password=encrypt_secret(body.agent_password) if body.agent_password else None,
            credentials_extra_json=extra,
            is_active=True,
            status="connected",
            created_by_user_id=user_id,
        )
        db.add(conn)
    db.flush()

    # Asset-type the new asset should live as. OS-level integrations
    # (windows/linux/DO/cisco) represent the host itself; DB/cloud/identity
    # integrations represent application-level services on top of the host
    # and need their OWN co-located asset rows (so they appear distinctly
    # in the IP group / Host-Applications panel and can be ticked into a
    # room scan independently).
    _OS_HOST_PLATFORMS = {"windows", "linux", "digitalocean"}
    target_asset_type = (
        "infrastructure" if platform in _OS_HOST_PLATFORMS else "application"
    )

    # Also auto-create an Asset for this host so the customer can
    # immediately scan it.
    # Lookup order:
    #   1. explicit asset_id (sent by the /assets "Connect" button so
    #      the link is reliable even when operator types IP-vs-FQDN)
    #   2. host_name match — but ONLY when the existing asset has the
    #      same asset_type semantics (OS-host vs application). Without
    #      this gate, a Postgres wizard targeting 127.0.0.1 would silently
    #      bind to the existing Windows "host" asset at the same address,
    #      losing the Postgres service as a separate scannable peer.
    #   3. create a new asset (auto-discovered host or service)
    asset = None
    if body.asset_id is not None:
        asset = (
            db.query(ITAsset)
            .filter(ITAsset.id == int(body.asset_id),
                    ITAsset.tenant_id == tenant_id)
            .first()
        )
    if asset is None:
        # Case-insensitive hostname match, scoped to compatible asset_type.
        # An OS wizard binds only to infrastructure rows; an app wizard
        # binds only to application rows (same hostname, different service).
        # That way: typing the same IP for the host AND for a co-located
        # DB creates two rows — one infrastructure, one application —
        # which is what the room-scan panel needs to surface as peers.
        hn = (body.hostname or "").strip()
        if hn:
            asset = (
                db.query(ITAsset)
                .filter(
                    ITAsset.tenant_id == tenant_id,
                    func.lower(ITAsset.host_name) == hn.lower(),
                    ITAsset.asset_type == target_asset_type,
                )
                .first()
            )
    # Block B/D — always probe OS at handshake time, even if the asset
    # already exists. Banker may have onboarded the asset previously with
    # vague CMDB OS data ("Windows 11") — we want to refresh to the exact
    # build ("windows-11-23H2") now that we have working credentials.
    # The probe is best-effort; failure preserves whatever data was there.
    from grc.modules.compliance_plugins.services.os_detector import (
        detect_for_runner_full,
        discover_services_for_runner,
    )
    os_family, os_version, os_normalized, os_build, os_edition = detect_for_runner_full(
        integration_type, test_creds or {}
    )
    # Probe what's ALSO running on this host (Linux/Windows only) so the
    # Host-Applications panel can surface promotable services right after
    # the wizard completes. DB/cloud/identity runners are themselves the
    # service — no inner discovery to do, the function returns []. Failures
    # never block — we still persist the asset with whatever OS info we got.
    discovered_services = discover_services_for_runner(integration_type, test_creds or {})

    asset_was_created = False
    if not asset:
        # Stamp the operator who started the wizard (from the signed
        # JWT payload) as owner. Without this the row has owner_id
        # IS NULL and the Risk Posture owner-scoped query filters it
        # out — operator sees "0 assets in tenant" on /risk-posture
        # even though /assets shows the row.
        owner_display = None
        if user_id is not None:
            from grc.models import GRCUser
            _owner = db.query(GRCUser).filter(GRCUser.id == user_id).first()
            if _owner is not None:
                owner_display = (getattr(_owner, "display_name", None)
                                 or getattr(_owner, "username", None))
        # If the operator didn't supply a distinctive display_label and we're
        # creating an application-level asset (e.g. Postgres at the same IP
        # as an existing Windows host), suffix the label with the platform
        # so the two rows are visually distinguishable in inventory.
        asset_label = label
        if (
            target_asset_type == "application"
            and not (body.display_label or "").strip()
            and asset_label == body.hostname
        ):
            asset_label = f"{body.hostname} ({platform})"
        asset = ITAsset(
            tenant_id=tenant_id,
            name=asset_label,
            description=f"Auto-discovered via Connect Wizard ({platform})",
            asset_type=target_asset_type,
            host_name=body.hostname,
            ip_address=(
                body.hostname
                if body.hostname and body.hostname.replace(".", "").isdigit()
                else None
            ),
            os_family=os_family,
            os_version=os_version,
            os_normalized=os_normalized,
            os_build=os_build,
            os_edition=os_edition,
            # Services we found running on this host (Linux/Windows only).
            # The Host-Applications panel's enrich_inventory step reads from
            # this column to surface promotable peers right after onboard.
            detected_software_json=(discovered_services or []),
            asset_role="host" if target_asset_type == "infrastructure" else "application",
            criticality="medium",
            status="active",
            owner_id=user_id,
            owner_name=owner_display,
        )
        db.add(asset)
        asset_was_created = True
    else:
        # Refresh existing asset's OS profile — only overwrite when probe
        # returned something. Don't clobber valid data with nulls if the
        # probe failed (e.g. credentials wrong now).
        if os_family:     asset.os_family = os_family
        if os_version:    asset.os_version = os_version
        if os_normalized: asset.os_normalized = os_normalized
        if os_build:      asset.os_build = os_build
        if os_edition:    asset.os_edition = os_edition
        # When the manually-added asset arrived with a blank host_name
        # (operator didn't fill the Component field) and we now have a
        # confirmed hostname from the wizard, populate it. Same for
        # ip_address when the hostname parses as a numeric IP. Without
        # this, the asset_pinned_connection lookup in _do_scan_all (which
        # joins console_url → host_name) can't find any connection for
        # this asset on the very next scan — operator sees "no integration
        # connection" error after a successful wizard run.
        if not (asset.host_name or "").strip() and (body.hostname or "").strip():
            asset.host_name = body.hostname.strip()
        if (
            not (asset.ip_address or "").strip()
            and body.hostname
            and body.hostname.replace(".", "").isdigit()
        ):
            asset.ip_address = body.hostname.strip()
        # Merge newly-discovered services with whatever was already there,
        # de-duped by software_key. Re-running the wizard against the same
        # host should refresh the listening-port snapshot — new services
        # added, but existing promote-to-peer links not lost.
        if discovered_services:
            existing = list(asset.detected_software_json or [])
            existing_keys = {
                (e.get("software_key") or "").lower()
                for e in existing if isinstance(e, dict)
            }
            merged = list(existing)
            for svc in discovered_services:
                k = (svc.get("software_key") or "").lower()
                if k and k not in existing_keys:
                    merged.append(svc)
                    existing_keys.add(k)
            asset.detected_software_json = merged

    db.commit()
    db.refresh(conn)
    if asset:
        db.refresh(asset)

    _STATUS[nonce] = {
        "state": "ready",
        "platform": platform,
        "tenant_id": tenant_id,
        "connection_id": conn.id,
        "asset_id": asset.id if asset else None,
        "asset_name": asset.name if asset else None,
        "asset_was_created": asset_was_created,
        "hostname": body.hostname,
        "os_name": body.os_name,
        "received_at": datetime.utcnow().isoformat(),
    }
    return {
        "status": "ok",
        "connection_id": conn.id,
        "asset_id": asset.id if asset else None,
        "asset_name": asset.name if asset else None,
        "asset_was_created": asset_was_created,
    }


# ─── Script builders ─────────────────────────────────────────────────────────

def _build_windows_script(token: str, handshake_url: str, tenant_id: int) -> str:
    # Per-tenant service account name avoids breaking another tenant's
    # credentials when the same machine is connected to multiple tenants.
    account_name = f"complivrs_t{tenant_id}"
    return f"""# Compliverse Connect Wizard — Windows installer
# This script: enables WinRM, creates a read-only service account named
# "{account_name}" (per-tenant — does NOT touch other tenants' accounts),
# opens the firewall, generates a TLS cert, and registers the server
# with Compliverse. Run as Administrator.

$ErrorActionPreference = "Stop"
$TenantToken = "{token}"
$HandshakeUrl = "{handshake_url}"
$AccountName = "{account_name}"

Write-Host ""
Write-Host "=== Compliverse Connect Wizard ===" -ForegroundColor Cyan

# Admin check
$id = [Security.Principal.WindowsIdentity]::GetCurrent()
$p = New-Object Security.Principal.WindowsPrincipal $id
if (-not $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {{
    Write-Host "ERROR: Run as Administrator." -ForegroundColor Red
    pause; exit 1
}}
Write-Host "[OK] Administrator confirmed" -ForegroundColor Green

# Step 1
Write-Host "[1/7] Enable PSRemoting..." -ForegroundColor Cyan
Enable-PSRemoting -Force -SkipNetworkProfileCheck | Out-Null
Write-Host "      Done." -ForegroundColor Green

# Step 2
Write-Host "[2/7] WinRM service running..." -ForegroundColor Cyan
Set-Service -Name WinRM -StartupType Automatic
Start-Service -Name WinRM -ErrorAction SilentlyContinue
Write-Host "      Done." -ForegroundColor Green

# Step 3
Write-Host "[3/7] TLS certificate..." -ForegroundColor Cyan
$existing = Get-ChildItem Cert:\\LocalMachine\\My | Where-Object {{ $_.Subject -like "CN=$env:COMPUTERNAME*" }} | Select-Object -First 1
if ($existing) {{ $cert = $existing }} else {{
    $cert = New-SelfSignedCertificate -DnsName $env:COMPUTERNAME -CertStoreLocation Cert:\\LocalMachine\\My
}}
$thumb = $cert.Thumbprint
Write-Host "      Thumbprint: $thumb" -ForegroundColor Green

# Step 4
Write-Host "[4/7] HTTPS listener on 5986..." -ForegroundColor Cyan
$el = & winrm enumerate winrm/config/Listener 2>&1 | Out-String
if ($el -match "Transport = HTTPS") {{ & winrm delete "winrm/config/Listener?Address=*+Transport=HTTPS" 2>&1 | Out-Null }}
$args = '@{{Hostname="' + $env:COMPUTERNAME + '";CertificateThumbprint="' + $thumb + '"}}'
& winrm create "winrm/config/Listener?Address=*+Transport=HTTPS" $args 2>&1 | Out-Null
Write-Host "      Done." -ForegroundColor Green

# Step 5
Write-Host "[5/7] Firewall port 5986..." -ForegroundColor Cyan
if (-not (Get-NetFirewallRule -DisplayName "WinRM HTTPS" -ErrorAction SilentlyContinue)) {{
    New-NetFirewallRule -DisplayName "WinRM HTTPS" -Direction Inbound -LocalPort 5986 -Protocol TCP -Action Allow | Out-Null
}}
Write-Host "      Done." -ForegroundColor Green

# Step 6 — per-tenant service account with one-time random password.
# Account name is $AccountName (e.g. complivrs_t4) so connecting a new
# tenant to a machine that already has another tenant's account does NOT
# rotate or break that other tenant's stored credentials.
Write-Host "[6/7] Service account ($AccountName)..." -ForegroundColor Cyan
$AgentPwd = -join ((33..126) | Get-Random -Count 24 | ForEach-Object {{[char]$_}})
$AgentSecure = ConvertTo-SecureString $AgentPwd -AsPlainText -Force
if (Get-LocalUser -Name $AccountName -ErrorAction SilentlyContinue) {{
    Set-LocalUser -Name $AccountName -Password $AgentSecure -PasswordNeverExpires $true
}} else {{
    New-LocalUser -Name $AccountName -Password $AgentSecure -PasswordNeverExpires -AccountNeverExpires | Out-Null
}}
foreach ($g in @("Administrators","Remote Management Users","Event Log Readers")) {{
    try {{ Add-LocalGroupMember -Group $g -Member $AccountName -ErrorAction Stop }} catch {{}}
}}
# Grant explicit access on PS session config
$sid = (New-Object System.Security.Principal.NTAccount($env:COMPUTERNAME, $AccountName)).Translate([System.Security.Principal.SecurityIdentifier]).Value
$cur = (Get-PSSessionConfiguration -Name Microsoft.PowerShell).SecurityDescriptorSddl
if ($cur -notmatch "GA;;;$sid") {{
    $new = $cur -replace '(D:[A-Z]*)', "`$1(A;;GA;;;$sid)"
    Set-PSSessionConfiguration -Name Microsoft.PowerShell -SecurityDescriptorSddl $new -Force -NoServiceRestart | Out-Null
    Restart-Service WinRM
}}
Write-Host "      Done." -ForegroundColor Green

# Step 7 — handshake back to Compliverse
Write-Host "[7/7] Registering with Compliverse..." -ForegroundColor Cyan
$body = @{{
    tenant_token       = $TenantToken
    hostname           = $env:COMPUTERNAME
    os_name            = (Get-CimInstance Win32_OperatingSystem).Caption
    winrm_endpoint     = "https://" + $env:COMPUTERNAME + ":5986/wsman"
    service_account    = $AccountName
    agent_password     = $AgentPwd
    cert_fingerprint   = $thumb
}} | ConvertTo-Json
try {{
    $resp = Invoke-RestMethod -Uri $HandshakeUrl -Method Post -ContentType "application/json" -Body $body
    Write-Host "      [OK] Server registered: connection_id=$($resp.connection_id)" -ForegroundColor Green
}} catch {{
    Write-Host "      ERROR contacting Compliverse: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}}

Write-Host ""
Write-Host "=== CONNECTED ===" -ForegroundColor Green
Write-Host "  Host         : $env:COMPUTERNAME"
Write-Host "  Compliverse  : registered (auto-asset created)"
Write-Host ""
Write-Host "Switch back to the Compliverse browser tab — it auto-detects this." -ForegroundColor Cyan
"""


def _build_linux_script(token: str, handshake_url: str, tenant_id: int) -> str:
    account_name = f"complivrs_t{tenant_id}"
    return f"""#!/usr/bin/env bash
# Compliverse Connect Wizard — Linux installer (read-only SSH access)
# Creates per-tenant user account "{account_name}" so multiple tenants
# can scan the same host without rotating each other's credentials.
set -e
TENANT_TOKEN="{token}"
HANDSHAKE_URL="{handshake_url}"
ACCOUNT="{account_name}"

echo "=== Compliverse Connect Wizard ==="

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: run as root (sudo)"
  exit 1
fi

# create scanner user
AGENT_PWD=$(openssl rand -base64 24)
if ! id $ACCOUNT >/dev/null 2>&1; then
  useradd -m -s /bin/bash $ACCOUNT
fi
echo "$ACCOUNT:$AGENT_PWD" | chpasswd

# install our SSH pubkey or password auth (one-time)
mkdir -p /home/$ACCOUNT/.ssh
chmod 700 /home/$ACCOUNT/.ssh

# ensure sshd allows password auth (minimal change)
sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd

# handshake
HOST="$(hostname)"
OS="$(. /etc/os-release && echo "$PRETTY_NAME")"
curl -fsS -X POST -H "Content-Type: application/json" \\
  -d "{{\\"tenant_token\\":\\"$TENANT_TOKEN\\",\\"hostname\\":\\"$HOST\\",\\"os_name\\":\\"$OS\\",\\"ssh_endpoint\\":\\"ssh://$HOST:22\\",\\"service_account\\":\\"$ACCOUNT\\",\\"agent_password\\":\\"$AGENT_PWD\\"}}" \\
  "$HANDSHAKE_URL"

echo ""
echo "=== CONNECTED ==="
echo "  Host: $HOST"
echo "Switch back to Compliverse — UI auto-detects."
"""
