import type { Assessment, ControlItem } from './types';

// Realistic banking internal-audit sample data. Replace with react-query
// results from /compliance/assessments in the real app.

export const SAMPLE_ASSESSMENTS: Assessment[] = [
  { id: 1, name: 'UBL Internal Audit 2025', type: 'Internal Audit', framework: 'internal_audit', status: 'in_progress', score: 50, total: 10, counts: { complied: 3, partial: 3, not_complied: 2, in_progress: 2, na: 0 }, assessedPct: 100, openGaps: 4, domainCount: 4, assessor: 'Sara Khan', due: 'Aug 15, 2025', source: 'UBL-Audit-Master.xlsx' },
  { id: 2, name: 'ISO 27001 Maturity Review', type: 'Maturity Model', framework: 'maturity', status: 'in_review', score: 72, total: 93, counts: { complied: 54, partial: 21, not_complied: 9, in_progress: 7, na: 2 }, assessedPct: 96, openGaps: 30, domainCount: 14, assessor: 'Imran Aziz', due: 'Sep 30, 2025', source: 'ISO27001-Maturity.xlsx' },
  { id: 3, name: 'Mobile Banking App — ASVS', type: 'OWASP ASVS', framework: 'asvs', status: 'in_progress', score: 58, total: 128, counts: { complied: 64, partial: 28, not_complied: 24, in_progress: 12, na: 0 }, assessedPct: 82, openGaps: 52, domainCount: 14, assessor: 'Hira Sheikh', due: 'Oct 10, 2025', source: 'ASVS-v4.0.3.xlsx' },
  { id: 4, name: 'Retail Web Portal — Testing', type: 'OWASP Testing', framework: 'owasp_testing', status: 'draft', score: 0, total: 0, counts: { complied: 0, partial: 0, not_complied: 0, in_progress: 0, na: 0 }, assessedPct: 0, openGaps: 0, domainCount: 0, assessor: 'Unassigned', due: 'Nov 05, 2025', source: 'OWASP-Testing.xlsx' },
  { id: 5, name: 'PCI-DSS v4.0 Self-Assessment', type: 'Standard', framework: 'standard', status: 'completed', score: 88, total: 64, counts: { complied: 52, partial: 6, not_complied: 2, in_progress: 0, na: 4 }, assessedPct: 100, openGaps: 8, domainCount: 12, assessor: 'Sara Khan', due: 'Jun 30, 2025', source: 'PCI-DSS-SAQ-D.xlsx' },
  { id: 6, name: 'CIS — Windows Server 2022', type: 'CIS Benchmark', framework: 'cis', status: 'in_progress', score: 76, total: 210, counts: { complied: 152, partial: 31, not_complied: 27, in_progress: 0, na: 0 }, assessedPct: 100, openGaps: 58, domainCount: 18, assessor: 'Bilal Raza', due: 'Sep 12, 2025', source: 'CIS-WinSrv2022-L1.xlsx' },
  { id: 7, name: 'NCA Essential Cybersecurity', type: 'NCA', framework: 'nca', status: 'in_review', score: 70, total: 114, counts: { complied: 68, partial: 24, not_complied: 14, in_progress: 8, na: 0 }, assessedPct: 91, openGaps: 38, domainCount: 5, assessor: 'Sara Khan', due: 'Oct 01, 2025', source: 'NCA-ECC-1.0.pdf' },
  { id: 8, name: 'PDPL Compliance Assessment', type: 'PDPL Assessment', framework: 'pdpl', status: 'in_progress', score: 61, total: 47, counts: { complied: 23, partial: 12, not_complied: 9, in_progress: 3, na: 0 }, assessedPct: 100, openGaps: 21, domainCount: 8, assessor: 'Hira Sheikh', due: 'Dec 15, 2025', source: 'PDPL-Toolkit.xlsx' },
];

export const SAMPLE_CONTROLS: ControlItem[] = [
  { id: 1, item_number: 'IA-001', area_domain: 'Information Security Governance', compliance_status: 'complied', priority: 'medium', responsible_party: 'CISO Office', timeline: 'Q1 2025', maturity_score: 4, risk_rating: 'Low', remediation_status: 'Closed', control_description: 'The board-approved information security policy is reviewed, updated, and formally ratified at least annually.', gaps_identified: 'None — the policy was reviewed and ratified by the board in January 2025.', proposed_solution: 'No action required. Continue annual review cycle.', evidence_reference: 'ISP-2025-v4.pdf', remarks: 'Signed off by the board risk committee.' },
  { id: 2, item_number: 'IA-002', area_domain: 'Information Security Governance', compliance_status: 'partially_complied', priority: 'medium', responsible_party: 'GRC Team', timeline: 'Q2 2025', maturity_score: 3, risk_rating: 'Medium', remediation_status: 'In Progress', control_description: 'Information security roles, responsibilities, and reporting lines are formally documented and communicated.', gaps_identified: 'A RACI matrix exists for on-prem operations but is missing for the cloud platform team.', proposed_solution: 'Extend the RACI matrix to cover cloud operations and publish on the intranet.', evidence_reference: 'Org-Chart-2024.xlsx', remarks: 'Draft RACI under review with cloud lead.' },
  { id: 3, item_number: 'IA-010', area_domain: 'Identity & Access Management', compliance_status: 'partially_complied', priority: 'high', responsible_party: 'IAM Team', timeline: 'Aug 2025', maturity_score: 3, risk_rating: 'High', remediation_status: 'In Progress', control_description: 'Privileged accounts are recertified at least quarterly by the relevant data and system owners.', gaps_identified: 'The Q2 recertification campaign covered 78% of privileged accounts; 22% remain overdue, including two domain-admin accounts.', proposed_solution: 'Automate the recertification campaign through the IGA platform and enforce a 30-day completion SLA with escalation.', evidence_reference: 'Recert-Q2-2025.csv', remarks: 'Two domain-admin accounts still unreviewed.' },
  { id: 4, item_number: 'IA-011', area_domain: 'Identity & Access Management', compliance_status: 'in_progress', priority: 'critical', responsible_party: 'Infrastructure', timeline: 'Sep 2025', maturity_score: 3, risk_rating: 'High', remediation_status: 'In Progress', control_description: 'Multi-factor authentication is enforced for all interactive access to the core banking system.', gaps_identified: 'MFA is enforced for 84% of users; batch and service interfaces to the core banking system are still pending.', proposed_solution: 'Roll out certificate-based authentication to the remaining service interfaces in wave 4.', evidence_reference: 'MFA-Coverage-Report.pdf', remarks: 'Phased rollout — currently wave 3 of 4.' },
  { id: 5, item_number: 'IA-012', area_domain: 'Identity & Access Management', compliance_status: 'not_complied', priority: 'high', responsible_party: 'IAM Team', timeline: 'Oct 2025', maturity_score: 1, risk_rating: 'High', remediation_status: 'Open', control_description: 'A complete and authoritative inventory of service and machine accounts is maintained, with a named owner per account.', gaps_identified: 'There is no authoritative inventory of service accounts; ownership is unknown for more than 40 accounts.', proposed_solution: 'Discover service accounts via directory scan, assign owners, and onboard credentials to the privileged-access vault.', evidence_reference: null, remarks: 'Linked to audit finding AF-2025-014.' },
  { id: 6, item_number: 'IA-020', area_domain: 'Vulnerability Management', compliance_status: 'partially_complied', priority: 'high', responsible_party: 'Branch IT', timeline: 'Sep 2025', maturity_score: 2, risk_rating: 'Medium', remediation_status: 'In Progress', control_description: 'Point-of-sale (POS) terminals are hardened to the approved CIS baseline before deployment to branches.', gaps_identified: 'The baseline is applied to all new terminals, but roughly 1,240 legacy terminals have not been re-imaged.', proposed_solution: 'Schedule phased re-imaging of the legacy fleet during quarterly maintenance windows.', evidence_reference: 'POS-Baseline-CIS.docx', remarks: 'Legacy fleet reaches end-of-life in Q4.' },
  { id: 7, item_number: 'IA-021', area_domain: 'Vulnerability Management', compliance_status: 'complied', priority: 'medium', responsible_party: 'SecOps', timeline: 'Q2 2025', maturity_score: 4, risk_rating: 'Low', remediation_status: 'Closed', control_description: 'Quarterly external ASV scans are performed against in-scope assets and pass per PCI-DSS requirements.', gaps_identified: 'None — the Q2 ASV scan passed with no failing items.', proposed_solution: 'No action required. Maintain the quarterly cadence.', evidence_reference: 'ASV-Q2-2025-Pass.pdf', remarks: 'Scan performed by an Approved Scanning Vendor.' },
  { id: 8, item_number: 'IA-022', area_domain: 'Vulnerability Management', compliance_status: 'not_complied', priority: 'critical', responsible_party: 'SecOps', timeline: 'Aug 2025', maturity_score: 2, risk_rating: 'High', remediation_status: 'Open', control_description: 'Critical-severity vulnerabilities are remediated within the 15-day service-level agreement.', gaps_identified: 'Mean time to remediate critical CVEs is currently 41 days; 12 critical findings are in breach of the SLA.', proposed_solution: 'Establish an emergency patch process and add a critical-CVE dashboard with live SLA timers.', evidence_reference: 'Vuln-SLA-Trend.png', remarks: 'Repeat finding carried over from the 2024 audit.' },
  { id: 9, item_number: 'IA-030', area_domain: 'Network & ATM Security', compliance_status: 'complied', priority: 'medium', responsible_party: 'Network Team', timeline: 'H1 2025', maturity_score: 4, risk_rating: 'Low', remediation_status: 'Closed', control_description: 'Firewall rule sets are formally reviewed every six months and stale or overly permissive rules are removed.', gaps_identified: 'None — the H1 review is complete and 36 stale rules were removed.', proposed_solution: 'No action required. Next review is due in H2.', evidence_reference: 'FW-Review-H1-2025.xlsx', remarks: 'Reviewed jointly with SecOps.' },
  { id: 10, item_number: 'IA-031', area_domain: 'Network & ATM Security', compliance_status: 'in_progress', priority: 'high', responsible_party: 'Network Team', timeline: 'Sep 2025', maturity_score: 3, risk_rating: 'Medium', remediation_status: 'In Progress', control_description: 'The ATM network segment enforces egress filtering and is logically isolated from the corporate LAN.', gaps_identified: 'Egress filtering is deployed at 312 of 410 ATM sites; the remaining 98 sites are pending.', proposed_solution: 'Complete the rollout to the remaining 98 sites and validate isolation with a segmentation penetration test.', evidence_reference: 'ATM-Segmentation-Plan.pdf', remarks: 'Linked to ATM audit finding AF-2025-031.' },
];

export const FRAMEWORK_TABS: { key: string; label: string }[] = [
  { key: 'overview', label: 'Overview' },
  { key: 'internal_audit', label: 'Internal Audit' },
  { key: 'maturity', label: 'Maturity Model' },
  { key: 'asvs', label: 'OWASP ASVS' },
  { key: 'owasp_testing', label: 'OWASP Testing' },
  { key: 'standard', label: 'Standard' },
  { key: 'nca', label: 'NCA' },
  { key: 'pdpl', label: 'PDPL Assessment' },
  { key: 'digital_ops_maturity', label: 'Digital Operations Maturity' },
  { key: 'dpia', label: 'DPIA / PIA' },
  // Cyber Security section templates (one page each).
  { key: 'cs_mobile', label: 'Mobile App Security' },
  { key: 'cs_csir', label: 'CSIR Maturity' },
  { key: 'cs_cti', label: 'CTI Maturity' },
  { key: 'cs_incident', label: 'Incident Management' },
  { key: 'cs_itsecops', label: 'IT Security Operations' },
  { key: 'cs_kpi', label: 'KPI Report' },
  // NCA section templates.
  { key: 'nca_vuln', label: 'Vulnerability Register' },
  { key: 'nca_audit', label: 'Audit Plan' },
  { key: 'nca_risk', label: 'Risk Management' },
];
