"""Connect Wizard — one-liner customer onboarding.

Flow:
  1. Authenticated customer hits POST /connect-wizard/issue-token
     → backend signs a JWT (15-min TTL) with their tenant_id
  2. Customer's browser polls GET /connect-wizard/status/{token}
  3. Customer runs the one-liner script on their Windows server. The
     script is served by GET /connect-wizard/win/{token} (returns
     PowerShell that does setup + POSTs handshake back).
  4. The script's last step POSTs to /connect-wizard/handshake which
     creates an IntegrationConnection row for the tenant.
  5. Browser poll picks up "ready" status and redirects to dashboard.

Security:
  - Token is signed with SESSION_SECRET, includes tenant_id + nonce + exp.
  - Handshake includes one-time agent password generated by the script
    (random per machine, never echoed back to the customer).
  - Connection rows are stored with credentials encrypted via Fernet
    (existing per-tenant encryption used elsewhere in the platform).
"""
from __future__ import annotations

import os
import secrets
import time
from datetime import datetime
from typing import Optional

import jwt
from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from grc.crypto import encrypt_secret
from grc.models import IntegrationConnection, get_db, ITAsset
from grc.routers.auth_router import get_user_primary_tenant, require_auth, GRCUser

router = APIRouter(prefix="/connect-wizard", tags=["Connect Wizard"])

SESSION_SECRET = os.environ.get("SESSION_SECRET", "dev-secret")
TOKEN_TTL_SECONDS = 15 * 60  # 15 minutes

# Hints rendered to the operator in the wizard UI when pre-flight rejects
# their credentials. Keep these in one place so we don't drift between
# the API and the React error banner.
_PREFLIGHT_HINTS = {
    "auth_failed": (
        "The username or password is wrong. For Windows: confirm the service "
        "account exists, is NOT locked, and that you typed the exact password "
        "set on the local account (Set-LocalUser as Admin if you reset it). "
        "For Linux: confirm the user can `ssh user@host` from a terminal first. "
        "For AWS: re-paste the access key + secret from the IAM console."
    ),
    "network_unreachable": (
        "The scanner cannot reach the target. For Windows: run "
        "`Test-NetConnection <host> -Port 5986` from this server. For Linux: "
        "run `nc -zv <host> 22`. Check firewall + that the service is running."
    ),
    "ssl_error": (
        "TLS handshake failed. The wizard auto-trusts self-signed certs, so "
        "this usually means the WinRM listener is HTTP-only (port 5985), not "
        "HTTPS (5986). Re-run the wizard installer to set up the HTTPS listener "
        "or switch the connection to HTTP."
    ),
    "config_error": (
        "A required field was missing or the runtime is misconfigured. "
        "Check that hostname, username, and password are all filled in."
    ),
    "unknown": (
        "Something went wrong during pre-flight. Check the server logs and "
        "verify the target host is reachable + the service account works."
    ),
}


# ─── Models ──────────────────────────────────────────────────────────────────

class IssueTokenIn(BaseModel):
    platform: str  # "windows" | "linux" | "aws"


class HandshakeIn(BaseModel):
    tenant_token: str
    hostname: str
    display_label: Optional[str] = None   # operator-friendly name for the UI
    os_name: Optional[str] = None
    winrm_endpoint: Optional[str] = None
    ssh_endpoint: Optional[str] = None
    service_account: Optional[str] = None
    agent_password: Optional[str] = None
    cert_fingerprint: Optional[str] = None


# In-memory status store. Production would use Redis; for v1 this is fine
# because tokens are short-lived and a process restart only invalidates
# the wizard session (customer just clicks "Connect" again).
_STATUS: dict[str, dict] = {}


def _sign(payload: dict) -> str:
    return jwt.encode(payload, SESSION_SECRET, algorithm="HS256")


def _verify(token: str) -> dict:
    try:
        return jwt.decode(token, SESSION_SECRET, algorithms=["HS256"])
    except jwt.PyJWTError as e:
        raise HTTPException(401, f"Invalid token: {e}")


# ─── Endpoints ───────────────────────────────────────────────────────────────

@router.post("/issue-token")
def issue_token(
    body: IssueTokenIn,
    db: Session = Depends(get_db),
    current_user: GRCUser = Depends(require_auth),
):
    """Issue a short-lived signed token for the wizard handshake.

    Frontend calls this when the customer picks a platform in the wizard.
    The token gets embedded in the one-liner script URL.
    """
    if body.platform not in {"windows", "linux", "aws", "digitalocean"}:
        raise HTTPException(422, "platform must be windows | linux | aws | digitalocean")
    tenant_id = get_user_primary_tenant(current_user, db)
    nonce = secrets.token_urlsafe(16)
    now = int(time.time())
    payload = {
        "tenant_id": tenant_id,
        "user_id": current_user.id,
        "platform": body.platform,
        "nonce": nonce,
        "iat": now,
        "exp": now + TOKEN_TTL_SECONDS,
    }
    token = _sign(payload)
    _STATUS[nonce] = {"state": "pending", "platform": body.platform, "tenant_id": tenant_id}
    return {
        "token": token,
        "nonce": nonce,
        "expires_in": TOKEN_TTL_SECONDS,
        "script_url": f"/grc/connect-wizard/{body.platform}/{token}",
    }


@router.get("/status/{nonce}")
def get_status(
    nonce: str,
    current_user: GRCUser = Depends(require_auth),
    db: Session = Depends(get_db),
):
    """Frontend polls this every ~3s while showing the one-liner. When the
    customer's machine POSTs to /handshake, this flips to ready."""
    rec = _STATUS.get(nonce)
    if not rec:
        raise HTTPException(404, "Unknown nonce or token expired")
    # Tenant scope check
    tenant_id = get_user_primary_tenant(current_user, db)
    if rec.get("tenant_id") != tenant_id:
        raise HTTPException(403, "Cross-tenant nonce access forbidden")
    return rec


@router.get("/windows/{token}", response_class=PlainTextResponse)
def windows_script(token: str):
    """Return the PowerShell one-liner installer with the tenant token baked in.

    Customer runs as Administrator. Script enables WinRM, creates a read-only
    PER-TENANT service account named ``complivrs_t{tenant_id}`` so two tenants
    connecting to the same machine cannot clobber each other's credentials.

    NOTE: served as text/plain so `iwr ... | iex` works in PowerShell.
    """
    payload = _verify(token)
    if payload.get("platform") != "windows":
        raise HTTPException(400, "Token is not for windows platform")
    handshake_url = "http://localhost:5000/grc/connect-wizard/handshake"
    return _build_windows_script(token, handshake_url, payload["tenant_id"])


@router.get("/linux/{token}", response_class=PlainTextResponse)
def linux_script(token: str):
    payload = _verify(token)
    if payload.get("platform") != "linux":
        raise HTTPException(400, "Token is not for linux platform")
    handshake_url = "http://localhost:5000/grc/connect-wizard/handshake"
    return _build_linux_script(token, handshake_url, payload["tenant_id"])


@router.post("/handshake")
def handshake(body: HandshakeIn, db: Session = Depends(get_db)):
    """Called by the customer's machine at the end of the install script.

    NOT authenticated by user session — authenticated by the signed JWT
    embedded in the script (only the customer who started the wizard could
    have received it).
    """
    payload = _verify(body.tenant_token)
    tenant_id = payload["tenant_id"]
    user_id = payload.get("user_id")
    nonce = payload["nonce"]
    platform = payload["platform"]

    # Defensive: strip any leading/trailing whitespace, tabs, and CR/LF from
    # operator-supplied strings. The Manual Credentials form is a common
    # source of accidental trailing tabs/newlines (tabbing between fields,
    # paste from a CSV cell, etc.) which Windows/Linux auth then rejects as
    # invalid credentials — a confusing failure mode for non-technical
    # operators who can SEE the values are "correct".
    def _clean(s: str | None) -> str | None:
        if s is None:
            return None
        # Strip leading/trailing whitespace + remove any embedded NBSP / tabs / newlines
        cleaned = s.strip().replace("\t", "").replace("\r", "").replace("\n", "")
        return cleaned or None

    body.hostname = _clean(body.hostname) or body.hostname
    body.display_label = _clean(body.display_label)
    body.service_account = _clean(body.service_account)
    body.agent_password = _clean(body.agent_password)
    body.winrm_endpoint = _clean(body.winrm_endpoint)
    body.ssh_endpoint = _clean(body.ssh_endpoint)

    # Build connection name — prefer operator-provided label, fall back to host.
    label = (body.display_label or body.hostname).strip()
    conn_name = f"{platform.capitalize()} — {label}"
    integration_type = {
        "windows": "windows_winrm",
        "linux": "linux_ssh",
        "aws": "aws_readonly",
        "digitalocean": "linux_ssh",
    }[platform]
    console_url = body.hostname
    if platform == "windows":
        console_port = 5986
    elif platform == "aws":
        console_port = 443
    else:  # linux, digitalocean
        console_port = 22
    prefix = f"WIZARD_{nonce.upper().replace('-','')[:10]}"

    # ──────────────────────────────────────────────────────────────────
    # LIVE PRE-FLIGHT
    #
    # Before we persist anything, prove the supplied credentials actually
    # work against the target host. This catches:
    #   • wrong password typed in manual creds form
    #   • account locked / disabled on Windows
    #   • WinRM service not running / firewall blocking port 5986
    #   • SSH not running / wrong port
    #   • AWS access key disabled or has wrong region
    #
    # Without this check, bad creds get stored, the wizard reports
    # "connected", and every scheduled scan silently fails with auth
    # errors — exactly the issue we hit on the first attempt today.
    # ──────────────────────────────────────────────────────────────────
    from grc.modules.compliance_plugins.services.preflight import preflight_check
    if platform == "windows":
        test_creds = {
            "winrm_endpoint": f"https://{body.hostname}:{console_port}/wsman",
            "winrm_username": body.service_account,
            "winrm_password": body.agent_password,
            "winrm_transport": "ntlm",
            "winrm_server_cert_validation": "ignore",
        }
    elif platform in ("linux", "digitalocean"):
        test_creds = {
            "ssh_host": body.hostname,
            "ssh_port": console_port,
            "ssh_username": body.service_account,
            "ssh_password": body.agent_password,
        }
    elif platform == "aws":
        # AwsForm packs the access key into `service_account` and the
        # secret key into `agent_password` so the same handshake schema
        # works for all platforms. hostname carries the AWS region label
        # (e.g. "aws-us-east-1" or "Production AWS").
        test_creds = {
            "aws_access_key_id": body.service_account,
            "aws_secret_access_key": body.agent_password,
            "aws_region": (body.os_name or "").replace("AWS Account · ", "").strip() or "us-east-1",
        }
    else:
        test_creds = None

    if test_creds is not None:
        pf = preflight_check(integration_type, test_creds)
        if not pf.ok:
            raise HTTPException(
                status_code=400,
                detail={
                    "preflight_failed": True,
                    "code": pf.code,
                    "message": pf.detail,
                    "hint": _PREFLIGHT_HINTS.get(pf.code, "Review credentials and target host configuration."),
                },
            )

    existing = (
        db.query(IntegrationConnection)
        .filter(
            IntegrationConnection.tenant_id == tenant_id,
            IntegrationConnection.connection_name == conn_name,
        )
        .first()
    )
    if existing:
        conn = existing
        conn.console_url = console_url
        conn.console_port = console_port
        conn.username = body.service_account or f"complivrs_t{tenant_id}"
        conn.password = encrypt_secret(body.agent_password)
        conn.status = "connected"
        conn.is_active = True
    else:
        conn = IntegrationConnection(
            tenant_id=tenant_id,
            integration_type=integration_type,
            connection_name=conn_name,
            console_url=console_url,
            console_port=console_port,
            auth_method="basic",
            credential_env_prefix=prefix,
            username=body.service_account or f"complivrs_t{tenant_id}",
            password=encrypt_secret(body.agent_password),
            is_active=True,
            status="connected",
            created_by_user_id=user_id,
        )
        db.add(conn)
    db.flush()

    # Also auto-create an Asset for this host so the customer can
    # immediately scan it.
    asset = (
        db.query(ITAsset)
        .filter(
            ITAsset.tenant_id == tenant_id,
            ITAsset.host_name == body.hostname,
        )
        .first()
    )
    if not asset:
        asset = ITAsset(
            tenant_id=tenant_id,
            name=label,
            description=f"Auto-discovered via Connect Wizard ({platform})",
            asset_type="infrastructure",
            host_name=body.hostname,
            criticality="medium",
            status="active",
        )
        db.add(asset)

    db.commit()
    db.refresh(conn)
    if asset:
        db.refresh(asset)

    _STATUS[nonce] = {
        "state": "ready",
        "platform": platform,
        "tenant_id": tenant_id,
        "connection_id": conn.id,
        "asset_id": asset.id if asset else None,
        "hostname": body.hostname,
        "os_name": body.os_name,
        "received_at": datetime.utcnow().isoformat(),
    }
    return {"status": "ok", "connection_id": conn.id, "asset_id": asset.id if asset else None}


# ─── Script builders ─────────────────────────────────────────────────────────

def _build_windows_script(token: str, handshake_url: str, tenant_id: int) -> str:
    # Per-tenant service account name avoids breaking another tenant's
    # credentials when the same machine is connected to multiple tenants.
    account_name = f"complivrs_t{tenant_id}"
    return f"""# Compliverse Connect Wizard — Windows installer
# This script: enables WinRM, creates a read-only service account named
# "{account_name}" (per-tenant — does NOT touch other tenants' accounts),
# opens the firewall, generates a TLS cert, and registers the server
# with Compliverse. Run as Administrator.

$ErrorActionPreference = "Stop"
$TenantToken = "{token}"
$HandshakeUrl = "{handshake_url}"
$AccountName = "{account_name}"

Write-Host ""
Write-Host "=== Compliverse Connect Wizard ===" -ForegroundColor Cyan

# Admin check
$id = [Security.Principal.WindowsIdentity]::GetCurrent()
$p = New-Object Security.Principal.WindowsPrincipal $id
if (-not $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {{
    Write-Host "ERROR: Run as Administrator." -ForegroundColor Red
    pause; exit 1
}}
Write-Host "[OK] Administrator confirmed" -ForegroundColor Green

# Step 1
Write-Host "[1/7] Enable PSRemoting..." -ForegroundColor Cyan
Enable-PSRemoting -Force -SkipNetworkProfileCheck | Out-Null
Write-Host "      Done." -ForegroundColor Green

# Step 2
Write-Host "[2/7] WinRM service running..." -ForegroundColor Cyan
Set-Service -Name WinRM -StartupType Automatic
Start-Service -Name WinRM -ErrorAction SilentlyContinue
Write-Host "      Done." -ForegroundColor Green

# Step 3
Write-Host "[3/7] TLS certificate..." -ForegroundColor Cyan
$existing = Get-ChildItem Cert:\\LocalMachine\\My | Where-Object {{ $_.Subject -like "CN=$env:COMPUTERNAME*" }} | Select-Object -First 1
if ($existing) {{ $cert = $existing }} else {{
    $cert = New-SelfSignedCertificate -DnsName $env:COMPUTERNAME -CertStoreLocation Cert:\\LocalMachine\\My
}}
$thumb = $cert.Thumbprint
Write-Host "      Thumbprint: $thumb" -ForegroundColor Green

# Step 4
Write-Host "[4/7] HTTPS listener on 5986..." -ForegroundColor Cyan
$el = & winrm enumerate winrm/config/Listener 2>&1 | Out-String
if ($el -match "Transport = HTTPS") {{ & winrm delete "winrm/config/Listener?Address=*+Transport=HTTPS" 2>&1 | Out-Null }}
$args = '@{{Hostname="' + $env:COMPUTERNAME + '";CertificateThumbprint="' + $thumb + '"}}'
& winrm create "winrm/config/Listener?Address=*+Transport=HTTPS" $args 2>&1 | Out-Null
Write-Host "      Done." -ForegroundColor Green

# Step 5
Write-Host "[5/7] Firewall port 5986..." -ForegroundColor Cyan
if (-not (Get-NetFirewallRule -DisplayName "WinRM HTTPS" -ErrorAction SilentlyContinue)) {{
    New-NetFirewallRule -DisplayName "WinRM HTTPS" -Direction Inbound -LocalPort 5986 -Protocol TCP -Action Allow | Out-Null
}}
Write-Host "      Done." -ForegroundColor Green

# Step 6 — per-tenant service account with one-time random password.
# Account name is $AccountName (e.g. complivrs_t4) so connecting a new
# tenant to a machine that already has another tenant's account does NOT
# rotate or break that other tenant's stored credentials.
Write-Host "[6/7] Service account ($AccountName)..." -ForegroundColor Cyan
$AgentPwd = -join ((33..126) | Get-Random -Count 24 | ForEach-Object {{[char]$_}})
$AgentSecure = ConvertTo-SecureString $AgentPwd -AsPlainText -Force
if (Get-LocalUser -Name $AccountName -ErrorAction SilentlyContinue) {{
    Set-LocalUser -Name $AccountName -Password $AgentSecure -PasswordNeverExpires $true
}} else {{
    New-LocalUser -Name $AccountName -Password $AgentSecure -PasswordNeverExpires -AccountNeverExpires | Out-Null
}}
foreach ($g in @("Administrators","Remote Management Users","Event Log Readers")) {{
    try {{ Add-LocalGroupMember -Group $g -Member $AccountName -ErrorAction Stop }} catch {{}}
}}
# Grant explicit access on PS session config
$sid = (New-Object System.Security.Principal.NTAccount($env:COMPUTERNAME, $AccountName)).Translate([System.Security.Principal.SecurityIdentifier]).Value
$cur = (Get-PSSessionConfiguration -Name Microsoft.PowerShell).SecurityDescriptorSddl
if ($cur -notmatch "GA;;;$sid") {{
    $new = $cur -replace '(D:[A-Z]*)', "`$1(A;;GA;;;$sid)"
    Set-PSSessionConfiguration -Name Microsoft.PowerShell -SecurityDescriptorSddl $new -Force -NoServiceRestart | Out-Null
    Restart-Service WinRM
}}
Write-Host "      Done." -ForegroundColor Green

# Step 7 — handshake back to Compliverse
Write-Host "[7/7] Registering with Compliverse..." -ForegroundColor Cyan
$body = @{{
    tenant_token       = $TenantToken
    hostname           = $env:COMPUTERNAME
    os_name            = (Get-CimInstance Win32_OperatingSystem).Caption
    winrm_endpoint     = "https://" + $env:COMPUTERNAME + ":5986/wsman"
    service_account    = $AccountName
    agent_password     = $AgentPwd
    cert_fingerprint   = $thumb
}} | ConvertTo-Json
try {{
    $resp = Invoke-RestMethod -Uri $HandshakeUrl -Method Post -ContentType "application/json" -Body $body
    Write-Host "      [OK] Server registered: connection_id=$($resp.connection_id)" -ForegroundColor Green
}} catch {{
    Write-Host "      ERROR contacting Compliverse: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}}

Write-Host ""
Write-Host "=== CONNECTED ===" -ForegroundColor Green
Write-Host "  Host         : $env:COMPUTERNAME"
Write-Host "  Compliverse  : registered (auto-asset created)"
Write-Host ""
Write-Host "Switch back to the Compliverse browser tab — it auto-detects this." -ForegroundColor Cyan
"""


def _build_linux_script(token: str, handshake_url: str, tenant_id: int) -> str:
    account_name = f"complivrs_t{tenant_id}"
    return f"""#!/usr/bin/env bash
# Compliverse Connect Wizard — Linux installer (read-only SSH access)
# Creates per-tenant user account "{account_name}" so multiple tenants
# can scan the same host without rotating each other's credentials.
set -e
TENANT_TOKEN="{token}"
HANDSHAKE_URL="{handshake_url}"
ACCOUNT="{account_name}"

echo "=== Compliverse Connect Wizard ==="

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: run as root (sudo)"
  exit 1
fi

# create scanner user
AGENT_PWD=$(openssl rand -base64 24)
if ! id $ACCOUNT >/dev/null 2>&1; then
  useradd -m -s /bin/bash $ACCOUNT
fi
echo "$ACCOUNT:$AGENT_PWD" | chpasswd

# install our SSH pubkey or password auth (one-time)
mkdir -p /home/$ACCOUNT/.ssh
chmod 700 /home/$ACCOUNT/.ssh

# ensure sshd allows password auth (minimal change)
sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd

# handshake
HOST="$(hostname)"
OS="$(. /etc/os-release && echo "$PRETTY_NAME")"
curl -fsS -X POST -H "Content-Type: application/json" \\
  -d "{{\\"tenant_token\\":\\"$TENANT_TOKEN\\",\\"hostname\\":\\"$HOST\\",\\"os_name\\":\\"$OS\\",\\"ssh_endpoint\\":\\"ssh://$HOST:22\\",\\"service_account\\":\\"$ACCOUNT\\",\\"agent_password\\":\\"$AGENT_PWD\\"}}" \\
  "$HANDSHAKE_URL"

echo ""
echo "=== CONNECTED ==="
echo "  Host: $HOST"
echo "Switch back to Compliverse — UI auto-detects."
"""
