"""Smoke test for the CIS Benchmark PDF ingestion pipeline.

Generates a tiny synthetic 3-rule CIS-style PDF with reportlab, runs it
through the full pipeline (extract → split → fields → check synthesis →
upsert), and asserts:
  - exactly 3 rules extracted
  - parent/child tree wires up correctly (1 → 1.1 → 1.1.1)
  - severity / runner_type heuristics fire
  - check_definition synthesis populates a real command for the AWS rule
  - re-running on the same PDF is idempotent (no duplicates)

Usage:  python3 scripts/test_cis_pdf_ingest.py
Exits non-zero on any assertion failure so CI / agents can gate on it.
"""
from __future__ import annotations

import io
import os
import sys
import pathlib

# Make the backend package importable when run from repo root.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / ".migration-backup" / "backend"))

# Use a separate sqlite DB for the smoke test so we never pollute the
# real Postgres rows. Set BEFORE importing grc.* so the engine binds to
# this URL on first import.
TEST_DB_URL = "sqlite:///:memory:"
os.environ["DATABASE_URL"] = TEST_DB_URL

from reportlab.lib.pagesizes import letter  # noqa: E402
from reportlab.pdfgen import canvas  # noqa: E402
from sqlalchemy import create_engine  # noqa: E402
from sqlalchemy.orm import sessionmaker  # noqa: E402

from grc.models import Base, CompliancePlugin, CisIngestJob  # noqa: E402
from grc.modules.compliance_plugins.pdf_ingest.pipeline import ingest_pdf  # noqa: E402


# Real CIS PDFs put each section LABEL on its own line, then the body
# below it. Our synthetic PDF mirrors that exactly so the section
# splitter (^\s*Label\s*:?\s*$) fires.
SYNTHETIC_RULES = [
    (
        "1",
        "Identity and Access Management",
        [
            "Description",
            "Top-level IAM controls.",
        ],
    ),
    (
        "1.1",
        "Ensure root account uses MFA (Automated)",
        [
            "Description",
            "The root account must have MFA enabled.",
            "Rationale",
            "Root account compromise is catastrophic; MFA mitigates credential theft.",
            "Audit",
            "Run aws iam get-account-summary and inspect the AccountMFAEnabled key.",
            "Remediation",
            "Enable a hardware MFA device for the root account in the IAM console.",
            "References",
            "1. https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html",
            "CIS Controls",
            "Controls 5.2, 6.5",
        ],
    ),
    (
        "1.1.1",
        "Ensure password minimum length is 14 characters (Automated)",
        [
            "Description",
            "The system password policy must enforce a 14-character minimum.",
            "Rationale",
            "Short passwords are trivially brute-forced.",
            "Audit",
            "Run grep '^minlen' /etc/security/pwquality.conf and verify the value is 14.",
            "Remediation",
            "Edit /etc/security/pwquality.conf and set minlen = 14.",
            "References",
            "1. https://example.org/pwquality",
            "CIS Controls",
            "Controls 5.2",
        ],
    ),
]


def build_synthetic_pdf() -> bytes:
    """Render a fake CIS benchmark PDF with a title page + 3 rules."""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    # ---- title page ----
    c.setFont("Helvetica-Bold", 18)
    c.drawString(72, height - 100, "CIS Synthetic Test Benchmark v1.0.0")
    c.setFont("Helvetica", 11)
    c.drawString(72, height - 130, "Generated by scripts/test_cis_pdf_ingest.py")
    c.showPage()

    # ---- one rule per page ----
    for rule_id, title, lines in SYNTHETIC_RULES:
        c.setFont("Helvetica-Bold", 12)
        # Heading line — the regex requires "<id> (Lx) <title>" or "<id> <title>"
        heading = f"{rule_id} (L1) {title}" if "Ensure" in title else f"{rule_id} {title}"
        c.drawString(72, height - 80, heading)
        c.setFont("Helvetica", 10)
        y = height - 110
        for line in lines:
            c.drawString(72, y, line[:110])
            y -= 14
        c.showPage()
    c.save()
    return buf.getvalue()


def main() -> int:
    print("[smoke] building synthetic CIS PDF…")
    pdf_bytes = build_synthetic_pdf()
    print(f"[smoke] PDF size = {len(pdf_bytes)} bytes")

    # Fresh in-memory sqlite + create all tables.
    engine = create_engine(TEST_DB_URL)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    db = Session()

    print("[smoke] running pipeline…")
    job = ingest_pdf(
        db,
        pdf_bytes,
        original_filename="cis-synthetic-v1.pdf",
        tenant_id=None,
        uploaded_by=None,
    )

    # --- assertions --------------------------------------------------------
    errors: list[str] = []

    if job.status != "completed":
        errors.append(f"job.status = {job.status!r} (expected 'completed'); error_text={job.error_text!r}")
    if (job.rules_extracted or 0) != len(SYNTHETIC_RULES):
        errors.append(f"rules_extracted = {job.rules_extracted} (expected {len(SYNTHETIC_RULES)})")
    if (job.rules_inserted or 0) != len(SYNTHETIC_RULES):
        errors.append(f"rules_inserted = {job.rules_inserted} (expected {len(SYNTHETIC_RULES)})")

    rows = (
        db.query(CompliancePlugin)
        .filter(CompliancePlugin.source_ingest_job_id == job.id)
        .all()
    )
    by_rid = {r.rule_id: r for r in rows}
    for expected_rid in ("1", "1.1", "1.1.1"):
        if expected_rid not in by_rid:
            errors.append(f"missing rule '{expected_rid}' (got: {sorted(by_rid)})")

    if "1" in by_rid and by_rid["1"].parent_plugin_id is not None:
        errors.append(f"rule '1' should have no parent, got parent_plugin_id={by_rid['1'].parent_plugin_id}")
    if "1.1" in by_rid and by_rid["1.1"].parent_plugin_id != by_rid["1"].id:
        errors.append(f"rule '1.1' parent should be rule '1' ({by_rid['1'].id}), got {by_rid['1.1'].parent_plugin_id}")
    if "1.1.1" in by_rid and by_rid["1.1.1"].parent_plugin_id != by_rid["1.1"].id:
        errors.append(f"rule '1.1.1' parent should be rule '1.1' ({by_rid['1.1'].id}), got {by_rid['1.1.1'].parent_plugin_id}")

    if "1.1" in by_rid:
        r = by_rid["1.1"]
        if r.runner_type != "aws_readonly":
            errors.append(f"rule '1.1' runner_type = {r.runner_type!r} (expected 'aws_readonly')")
        if r.severity != "critical":
            errors.append(f"rule '1.1' severity = {r.severity!r} (expected 'critical' — keyword 'mfa'/'root account')")
        if not (r.check_definition or {}).get("service") == "iam":
            errors.append(f"rule '1.1' check_definition.service = {(r.check_definition or {}).get('service')!r} (expected 'iam')")

    if "1.1.1" in by_rid:
        r = by_rid["1.1.1"]
        if r.runner_type != "linux_ssh":
            errors.append(f"rule '1.1.1' runner_type = {r.runner_type!r} (expected 'linux_ssh')")
        cmd = (r.check_definition or {}).get("command") or ""
        if "minlen" not in cmd:
            errors.append(f"rule '1.1.1' check_definition.command = {cmd!r} (expected to contain 'minlen')")

    # All auto-generated checks must be flagged for review.
    for rid in ("1.1", "1.1.1"):
        if rid in by_rid and by_rid[rid].review_status != "pending_review":
            errors.append(f"rule '{rid}' review_status = {by_rid[rid].review_status!r} (auto-generated must be 'pending_review')")
        if rid in by_rid and by_rid[rid].enabled:
            errors.append(f"rule '{rid}' enabled = True (auto-generated must default to disabled)")

    # Idempotency: re-ingest the exact same PDF, expect 0 inserts.
    job2 = ingest_pdf(
        db,
        pdf_bytes,
        original_filename="cis-synthetic-v1.pdf",
        tenant_id=None,
        uploaded_by=None,
    )
    if (job2.rules_inserted or 0) != 0:
        errors.append(f"re-ingest inserted {job2.rules_inserted} new rules (expected 0; pipeline must upsert)")
    if (job2.rules_updated or 0) != len(SYNTHETIC_RULES):
        errors.append(f"re-ingest updated {job2.rules_updated} rules (expected {len(SYNTHETIC_RULES)})")
    final_count = db.query(CompliancePlugin).count()
    if final_count != len(SYNTHETIC_RULES):
        errors.append(f"row count after re-ingest = {final_count} (expected {len(SYNTHETIC_RULES)} — duplicates created)")

    # --- report ------------------------------------------------------------
    print()
    print(f"[smoke] job: status={job.status} pages={job.page_count} rules_extracted={job.rules_extracted}"
          f" inserted={job.rules_inserted} flagged={job.rules_flagged} ocr_pages={job.ocr_pages}")
    print(f"[smoke] tree: " + ", ".join(f"{rid}->parent={by_rid[rid].parent_plugin_id}" for rid in sorted(by_rid)))
    print(f"[smoke] severities: " + ", ".join(f"{rid}={by_rid[rid].severity}" for rid in sorted(by_rid)))
    print(f"[smoke] runners: " + ", ".join(f"{rid}={by_rid[rid].runner_type}" for rid in sorted(by_rid)))

    if errors:
        print(f"\n[smoke] FAILED ({len(errors)} assertion errors):")
        for e in errors:
            print(f"  - {e}")
        return 1
    print("\n[smoke] OK — pipeline end-to-end passes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
