"""
Single source of truth for workflow graph validation.

This module is a 1:1 Python mirror of the frontend canvas validator at
    artifacts/grc-frontend/src/app/(dashboard)/workflow-engine/components/types.ts
                lines 666-971  (PATH_TO_RESOURCE_FRONTEND, PRIMARY_TRIGGER_FRONTEND,
                                inferTriggerEventFromActionName,
                                getTriggerEventForFirstNode,
                                validateWorkflowGraph)

DO NOT EDIT THIS FILE WITHOUT EDITING types.ts FIRST.
The seeder (scripts/seed_workflows.py) uses this module as its pre-flight gate,
so any drift between this file and types.ts will silently produce workflows
that the canvas refuses to mark as valid (red "Not a trigger" badge).

Contract scope: BOOLEAN VALIDITY + COMPUTED TRIGGER EVENT must match types.ts
exactly. Human-readable error strings in `validate_graph` are intentionally
abbreviated (the seeder only logs them) and may differ from the longer UX
copy in types.ts:966-967. If you need the exact UX strings, mirror them
verbatim from validateWorkflowGraph.

If the frontend tables change:
  1. Update PATH_TO_RESOURCE / PRIMARY_TRIGGER / TRIGGER_EVENT_MAP below.
  2. Re-run scripts/seed_workflows.py — pre-flight will fail loudly if any
     existing recipe stops resolving.
"""
from __future__ import annotations

from typing import Any

# ─────────────────────────────────────────────────────────────────────────────
# Mirror of types.ts:666-723 (PATH_TO_RESOURCE_FRONTEND).
# Order matters: longest / most-specific prefix first, since we use startswith.
# ─────────────────────────────────────────────────────────────────────────────
PATH_TO_RESOURCE: list[tuple[str, str]] = [
    # Compliance submodules
    ("compliance.control_library",       "compliance.control_library"),
    ("compliance.statements",            "compliance.statements"),
    ("compliance.evidence",              "compliance.evidence"),
    ("compliance.evidence_requirements", "compliance.evidence_requirements"),
    ("compliance.assessments",           "compliance.assessments"),
    ("compliance.controls",              "compliance.controls"),
    ("compliance.frameworks",            "compliance.frameworks"),
    ("compliance.plugin_runs",           "compliance.plugin_runs"),
    ("compliance",                       "compliance"),
    # Vulnerability Management submodules
    ("vulnerability_management.vulnerabilities", "vulnmgmt.vulnerabilities"),
    ("vulnerability_management.departments",     "vulnmgmt.departments"),
    ("vulnerability_management.reports",         "vulnmgmt.reports"),
    ("vulnerability_management.sla_config",      "vulnmgmt.sla_config"),
    ("vulnerability_management",                 "vulnerabilities"),
    ("vuln_management",                          "vulnerabilities"),
    # Governance submodules
    ("governance.documents",          "governance.documents"),
    ("governance.committees",         "governance.committees"),
    ("governance.attestations",       "governance.attestations"),
    ("governance.clause_coverage",    "governance.clause_coverage"),
    ("governance.regulatory_changes", "governance.regulatory_changes"),
    ("governance.regulatory_feeds",   "governance.regulatory_feeds"),
    ("governance.regulatory",         "governance.regulatory"),
    ("governance.critical_rules",     "governance.critical_rules"),
    ("governance.patch_proposals",    "governance.patch_proposals"),
    ("governance",                    "governance"),
    # Risk Management submodules
    ("risk_management.incidents",          "risk.incidents"),
    ("risk_management.kris",               "risk.kris"),
    ("risk_management.risk_register",      "risk.risk_register"),
    ("risk_management.risk_assessments",   "risk.risk_assessments"),
    ("risk_management.risk_framework",     "risk.risk_framework"),
    ("risk_management.internal_controls",  "risk.internal_controls"),
    ("risk_management.mitigation_actions", "risk.mitigation_actions"),
    ("risk_management.vendor_risk",        "risk.vendor_risk"),
    ("risk_management.rcsa",               "risk.rcsa"),
    ("risk_management.appetite",           "risk.appetite"),
    ("risk_management.dependencies",       "risk.dependencies"),
    ("risk_management.reviews",            "risk.reviews"),
    ("risk_management.advanced_analytics", "risk.advanced_analytics"),
    ("risk_management",                    "risks"),
    ("erm.incident",                       "risk.incidents"),
    ("erm.risk",                           "risks"),
    ("erm",                                "risks"),
    # Other modules
    ("audit_management", "audits"),
    ("evidence_mgmt",    "compliance.evidence"),
    ("evidence",         "compliance.evidence"),
    ("assets",           "assets"),
    ("kri",              "risk.kris"),
    ("audits",           "audits"),
]

# ─────────────────────────────────────────────────────────────────────────────
# Mirror of types.ts:725-850 (PRIMARY_TRIGGER_FRONTEND).
# Maps "<resource>:<verb>" -> canonical trigger_event.
# ─────────────────────────────────────────────────────────────────────────────
PRIMARY_TRIGGER: dict[str, str] = {
    # Compliance
    "compliance.control_library:create": "compliance.control_library.create",
    "compliance.control_library:update": "compliance.control_library.update",
    "compliance.control_library:delete": "compliance.control_library.delete",
    "compliance.statements:create":      "compliance.statements.create",
    "compliance.statements:update":      "compliance.statements.update",
    "compliance.statements:delete":      "compliance.statements.delete",
    "compliance.evidence:create":        "compliance.evidence.create",
    "compliance.evidence:update":        "compliance.evidence.update",
    "compliance.evidence:delete":        "compliance.evidence.delete",
    "compliance.evidence:upload":        "compliance.evidence.upload",
    "compliance.evidence_requirements:create": "compliance.evidence_requirements.create",
    "compliance.evidence_requirements:update": "compliance.evidence_requirements.update",
    "compliance.evidence_requirements:delete": "compliance.evidence_requirements.delete",
    "compliance.assessments:create":  "compliance.assessments.create",
    "compliance.assessments:update":  "compliance.assessments.update",
    "compliance.assessments:delete":  "compliance.assessments.delete",
    "compliance.assessments:trigger": "compliance.assessments.trigger",
    "compliance.controls:create":     "compliance.controls.create",
    "compliance.controls:update":     "compliance.controls.update",
    "compliance.controls:delete":     "compliance.controls.delete",
    "compliance.frameworks:create":   "compliance.frameworks.create",
    "compliance.frameworks:update":   "compliance.frameworks.update",
    "compliance.frameworks:delete":   "compliance.frameworks.delete",
    "compliance.frameworks:upload":   "compliance.frameworks.upload",
    "compliance.plugin_runs:create":  "compliance.plugin_runs.create",
    "compliance.plugin_runs:update":  "compliance.plugin_runs.update",
    "compliance.plugin_runs:trigger": "compliance.plugin_runs.trigger",
    "compliance.plugin_runs:execute": "compliance.plugin_runs.execute",
    "compliance.plugin_runs:failed":  "compliance.plugin_runs.failed",
    # Vulnerability Management
    "vulnmgmt.vulnerabilities:create": "vulnmgmt.vulnerabilities.create",
    "vulnmgmt.vulnerabilities:update": "vulnmgmt.vulnerabilities.update",
    "vulnmgmt.vulnerabilities:delete": "vulnmgmt.vulnerabilities.delete",
    "vulnmgmt.departments:create": "vulnmgmt.departments.create",
    "vulnmgmt.departments:update": "vulnmgmt.departments.update",
    "vulnmgmt.departments:delete": "vulnmgmt.departments.delete",
    "vulnmgmt.reports:create":     "vulnmgmt.reports.create",
    "vulnmgmt.sla_config:create":  "vulnmgmt.sla_config.create",
    "vulnmgmt.sla_config:update":  "vulnmgmt.sla_config.update",
    "vulnmgmt.sla_config:delete":  "vulnmgmt.sla_config.delete",
    # Governance
    "governance.documents:create":  "governance.documents.create",
    "governance.documents:update":  "governance.documents.update",
    "governance.documents:delete":  "governance.documents.delete",
    "governance.documents:trigger": "governance.documents.trigger",
    "governance.documents:upload":  "governance.documents.upload",
    "governance.documents:approve": "governance.documents.approve",
    "governance.documents:reject":  "governance.documents.reject",
    "governance.committees:create":  "governance.committees.create",
    "governance.committees:update":  "governance.committees.update",
    "governance.committees:delete":  "governance.committees.delete",
    "governance.committees:trigger": "governance.committees.trigger",
    "governance.committees:upload":  "governance.committees.upload",
    "governance.attestations:create":  "governance.attestations.create",
    "governance.attestations:update":  "governance.attestations.update",
    "governance.attestations:delete":  "governance.attestations.delete",
    "governance.attestations:trigger": "governance.attestations.trigger",
    "governance.clause_coverage:create": "governance.clause_coverage.create",
    "governance.regulatory_changes:create": "governance.regulatory_changes.create",
    "governance.regulatory_changes:update": "governance.regulatory_changes.update",
    "governance.regulatory_changes:delete": "governance.regulatory_changes.delete",
    "governance.regulatory_feeds:create":   "governance.regulatory_feeds.create",
    "governance.regulatory_feeds:update":   "governance.regulatory_feeds.update",
    "governance.critical_rules:create":     "governance.critical_rules.create",
    "governance.critical_rules:update":     "governance.critical_rules.update",
    "governance.patch_proposals:create":    "governance.patch_proposals.create",
    "governance.patch_proposals:update":    "governance.patch_proposals.update",
    # Risk Management
    "risk.incidents:create": "risk.incidents.create",
    "risk.incidents:update": "risk.incidents.update",
    "risk.incidents:delete": "risk.incidents.delete",
    "risk.kris:create": "risk.kris.create",
    "risk.kris:update": "risk.kris.update",
    "risk.kris:delete": "risk.kris.delete",
    "risk.risk_register:create": "risk.risk_register.create",
    "risk.risk_register:update": "risk.risk_register.update",
    "risk.risk_register:delete": "risk.risk_register.delete",
    "risk.risk_assessments:create": "risk.risk_assessments.create",
    "risk.risk_assessments:update": "risk.risk_assessments.update",
    "risk.risk_assessments:delete": "risk.risk_assessments.delete",
    "risk.risk_framework:create": "risk.risk_framework.create",
    "risk.risk_framework:update": "risk.risk_framework.update",
    "risk.risk_framework:delete": "risk.risk_framework.delete",
    "risk.internal_controls:create": "risk.internal_controls.create",
    "risk.internal_controls:update": "risk.internal_controls.update",
    "risk.internal_controls:delete": "risk.internal_controls.delete",
    "risk.mitigation_actions:create": "risk.mitigation_actions.create",
    "risk.mitigation_actions:update": "risk.mitigation_actions.update",
    "risk.mitigation_actions:delete": "risk.mitigation_actions.delete",
    "risk.vendor_risk:create": "risk.vendor_risk.create",
    "risk.vendor_risk:update": "risk.vendor_risk.update",
    "risk.vendor_risk:delete": "risk.vendor_risk.delete",
    "risk.rcsa:create": "risk.rcsa.create",
    "risk.rcsa:update": "risk.rcsa.update",
    "risk.rcsa:delete": "risk.rcsa.delete",
    "risk.appetite:create": "risk.appetite.create",
    "risk.appetite:update": "risk.appetite.update",
    "risk.dependencies:create": "risk.dependencies.create",
    "risk.dependencies:update": "risk.dependencies.update",
    "risk.reviews:create": "risk.reviews.create",
    "risk.reviews:update": "risk.reviews.update",
    # Module-level fallbacks
    "risks:create": "risk_created",
    "risks:update": "risk_updated",
    "risks:delete": "risk_deleted",
    "vulnerabilities:create": "vulnerability_created",
    "vulnerabilities:update": "vulnerability_updated",
    "vulnerabilities:delete": "vulnerability_deleted",
    "assets:create": "asset_created",
    "assets:update": "asset_updated",
    "assets:delete": "asset_deleted",
    "governance:create":  "governance.create",
    "governance:update":  "assessment_status_change",
    "governance:delete":  "governance.delete",
    "governance:upload":  "governance.upload",
    "governance:approve": "governance.approve",
    "governance:reject":  "governance.reject",
    "governance:trigger": "policy_submitted_for_review",
    "compliance:create":  "compliance_gap_detected",
    "compliance:update":  "assessment_status_change",
    "compliance:delete":  "compliance.delete",
    "compliance:trigger": "compliance_gap_detected",
    "audits:create": "audit_finding_created",
    "audits:update": "audits.update",
    "audits:delete": "audits.delete",
}

TRIGGER_EVENT_MAP: dict[str, str] = {
    "manual_trigger":     "manual.trigger",
    "schedule_recurring": "scheduler.recurring",
    "webhook":            "workflow.webhook",
}

CRUD_VERBS = ("create", "update", "delete", "trigger")


def infer_trigger_event_from_action_name(action_name: str | None) -> str | None:
    """Mirror of inferTriggerEventFromActionName (types.ts:857-870)."""
    if not action_name or not action_name.startswith("platform_action."):
        return None
    parts = action_name.split(".")
    if len(parts) < 3:
        return None
    verb = parts[1]
    module_path = ".".join(parts[2:])
    resource: str | None = None
    for prefix, res in PATH_TO_RESOURCE:
        if module_path.startswith(prefix):
            resource = res
            break
    if not resource:
        return None
    verb_key = verb if verb in CRUD_VERBS else "update"
    return PRIMARY_TRIGGER.get(f"{resource}:{verb_key}")


def normalize_node_type(node: dict) -> str:
    """Mirror of normalizeBackendNode in page.tsx:69-89.
    Produces the canvas-side nodeType for a backend node row."""
    nt = node.get("node_type") or "action"
    if node.get("is_start") or node.get("node_key") == "start":
        nt = "start"
    if node.get("is_terminal") or node.get("node_key") == "end":
        nt = "end"
    return nt


def get_trigger_event_for_first_node(first_node: dict | None) -> str | None:
    """Mirror of getTriggerEventForFirstNode (types.ts:886-901)."""
    if not first_node:
        return None
    nt = normalize_node_type(first_node)
    cfg = first_node.get("config") or {}
    if nt == "start":
        tt = cfg.get("trigger_type") or ""
        if not tt:
            return None
        return TRIGGER_EVENT_MAP.get(tt, tt)
    if nt == "action":
        return infer_trigger_event_from_action_name(cfg.get("action_name") or "")
    return None


def validate_graph(nodes: list[dict], edges: list[dict]) -> tuple[bool, str, str | None]:
    """Mirror of validateWorkflowGraph (types.ts:924-971).
    Returns (ok, error_message_or_empty, computed_trigger_event_or_None).
    Edges use backend keys: source_node_key / target_node_key.
    """
    if not nodes:
        return False, "Graph has no nodes.", None
    has_work = any(
        n.get("node_key") != "start" and normalize_node_type(n) != "end"
        for n in nodes
    )
    if not has_work:
        return False, "Add at least one node after Start so the workflow has something to do.", None

    start_nodes = [
        n for n in nodes
        if n.get("node_key") == "start"
        or n.get("is_start") is True
        or normalize_node_type(n) == "start"
    ]
    if not start_nodes:
        return False, "Add a Start node to begin the workflow.", None
    start_node = next((n for n in start_nodes if n.get("node_key") == "start"), start_nodes[0])
    sk = start_node.get("node_key")
    start_edges = [e for e in edges if e.get("source_node_key") == sk]
    if not start_edges:
        return False, "Connect the Start node to the first action of your workflow.", None
    if len(start_edges) > 1:
        return False, "Start can only connect to one node. Remove the extra connections.", None
    target_key = start_edges[0].get("target_node_key")
    first_node = next((n for n in nodes if n.get("node_key") == target_key), None)
    if not first_node:
        return False, "The Start connection points to a node that no longer exists.", None
    computed = get_trigger_event_for_first_node(first_node)
    if not computed:
        nt = normalize_node_type(first_node)
        if nt == "action":
            return False, "First action is not a CRUD platform_action eligible for trigger inference.", None
        return False, "First node has no trigger_type configured.", None
    return True, "", computed


# ─────────────────────────────────────────────────────────────────────────────
# Helpers used by the seeder to enumerate every reachable trigger.
# ─────────────────────────────────────────────────────────────────────────────
def reachable_trigger_keys() -> list[tuple[str, str]]:
    """Return the list of (resource, verb) PRIMARY_TRIGGER keys that are
    actually reachable via inferTriggerEventFromActionName.

    Verbs not in CRUD_VERBS are coerced to 'update' by the validator, so
    keys like 'governance.documents:upload' / ':approve' / ':reject' are
    NOT reachable from a `platform_action.<verb>.*` node — they're filtered
    out here so the seeder doesn't try to use them.
    """
    out: list[tuple[str, str]] = []
    for key, expected in PRIMARY_TRIGGER.items():
        resource, _, verb = key.partition(":")
        if verb not in CRUD_VERBS:
            continue
        # Some keys are shadowed by an earlier entry in PATH_TO_RESOURCE
        # (e.g. compliance.evidence_requirements is shadowed by compliance.evidence
        # because .startswith() matches the shorter prefix first). Filter those
        # out — they cannot be reached via action_name inference.
        synth = synthesize_action_name(resource, verb)
        if synth and infer_trigger_event_from_action_name(synth) == expected:
            out.append((resource, verb))
    return out


def canonical_module_path_for_resource(resource: str) -> str | None:
    """Find the first prefix in PATH_TO_RESOURCE that maps to `resource`.
    Used by the seeder to synthesize a valid action_name modulePath."""
    for prefix, res in PATH_TO_RESOURCE:
        if res == resource:
            return prefix
    return None


def synthesize_action_name(resource: str, verb: str) -> str | None:
    """Build a platform_action.* string that resolves to (resource, verb).

    The validator splits on '.' and uses parts[2:] as modulePath, then walks
    PATH_TO_RESOURCE longest-first via startswith. So we just need a
    modulePath that starts with the canonical prefix for `resource` AND
    isn't accidentally prefixed by a more-specific entry in the table.
    """
    prefix = canonical_module_path_for_resource(resource)
    if not prefix:
        return None
    candidate = f"platform_action.{verb}.{prefix}"
    # Verify the validator agrees by round-tripping
    if infer_trigger_event_from_action_name(candidate) == PRIMARY_TRIGGER[f"{resource}:{verb}"]:
        return candidate
    # Fall back to appending a synthetic leaf segment
    candidate = f"platform_action.{verb}.{prefix}.event"
    if infer_trigger_event_from_action_name(candidate) == PRIMARY_TRIGGER[f"{resource}:{verb}"]:
        return candidate
    return None
