'use client';

export const dynamic = 'force-dynamic';

import { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { DataTable, MultiSelectDropdown, PageLoader } from '@/components/ui';
import { adminApi } from '@/lib/api';

interface AuditLogEntry {
  id: number;
  user_id: number | null;
  user_name: string;
  action: string;
  resource_type: string;
  resource_id: number | null;
  description: string;
  details: Record<string, unknown>;
  method?: string;
  path?: string;
  status_code?: number;
  duration_ms?: number;
  ip_address: string | null;
  timestamp: string;
  // v2 audit-AI: cached human-readable summary; lazily generated by
  // /admin/audit-logs/{id}/ai-summary the first time the row is opened.
  ai_summary?: string | null;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function UserAvatar({ name }: { name: string }) {
  const initials = name
    .split(/\s+/)
    .map((n) => n[0] ?? '')
    .join('')
    .toUpperCase()
    .slice(0, 2) || '?';
  return (
    <span className="inline-flex items-center justify-center w-7 h-7 rounded-full bg-primary-100 text-primary-700 text-xs font-semibold shrink-0 select-none">
      {initials}
    </span>
  );
}

const ACTION_CFG: Record<string, { bg: string; label: string }> = {
  create:         { bg: 'bg-emerald-50 text-emerald-700 border border-emerald-200', label: 'Create' },
  update:         { bg: 'bg-slate-50 text-slate-600 border border-slate-200',       label: 'Update' },
  delete:         { bg: 'bg-rose-50 text-rose-700 border border-rose-200',          label: 'Delete' },
  read:           { bg: 'bg-slate-50 text-slate-500 border border-slate-200',       label: 'Read'   },
  create_failed:  { bg: 'bg-amber-50 text-amber-700 border border-amber-200',       label: 'Create Failed' },
  update_failed:  { bg: 'bg-amber-50 text-amber-700 border border-amber-200',       label: 'Update Failed' },
  delete_failed:  { bg: 'bg-amber-50 text-amber-700 border border-amber-200',       label: 'Delete Failed' },
};

function ActionBadge({ action }: { action: string }) {
  const cfg = ACTION_CFG[action] ?? {
    bg: 'bg-slate-50 text-slate-600 border border-slate-200',
    label: action.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
  };
  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium whitespace-nowrap ${cfg.bg}`}>
      {cfg.label}
    </span>
  );
}

function fmtTs(ts: string) {
  const d = new Date(ts);
  return {
    date: d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }),
    time: d.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
  };
}

// ── Module / sub-module derivation ───────────────────────────────────────────
//
// The audit log records URL paths like `/grc/erm/risks/5` or
// `/grc/governance/documents/3/policy-statements`. We split the path into a
// module (first segment) and an optional sub-module (second segment when it
// isn't a numeric id), then look each up in the friendly-label maps below.
// Anything not in the maps falls back to title-cased text so the column never
// blank-renders.

const MODULE_LABELS: Record<string, string> = {
  erm: 'Risks & ERM',
  evidence: 'Evidence',
  'evidence-mgmt': 'Evidence',
  governance: 'Governance',
  compliance: 'Compliance',
  'vuln-management': 'Vulnerability Mgmt',
  vulnerabilities: 'Vulnerability Mgmt',
  frameworks: 'Frameworks',
  'framework-upload': 'Frameworks',
  certifications: 'Certifications',
  admin: 'Administration',
  auth: 'Authentication',
  'vendor-risk': 'Vendor Risk',
  vendor_risk: 'Vendor Risk',
  tasks: 'Critical Tasks',
  'critical-tasks': 'Critical Tasks',
  assets: 'Assets',
  'control-library': 'Control Library',
  controls: 'Controls',
  dashboard: 'Dashboard',
  'workflow-engine': 'Workflow Engine',
  workflow: 'Workflow Engine',
  chatbot: 'AI Assistant',
  complychat: 'AI Assistant',
  integrations: 'Integrations',
  'auditor-portal': 'Auditor Portal',
  audits: 'Auditor Portal',
  'is-projects': 'IS Projects',
  reports: 'Reports',
  documents: 'Documents',
  system: 'System',
  risks: 'Risks & ERM',
  // Issue Management — URL prefix `/issue-management/...` from the
  // issue_management module routers.
  'issue-management': 'Issue Management',
  // Criticality Assessments — `/criticality-assessments/...` for the
  // ISCA + IACA endpoints under Asset Management.
  'criticality-assessments': 'Criticality Assessments',
  // CIS Compliance Plugins — `/compliance-plugins/...` (library
  // listing, runs, benchmark-mappings, library-tree, scan-all, ingest).
  'compliance-plugins': 'CIS Compliance Plugins',
  // Connect Wizard — `/connect-wizard/...` (issue-token, status poll,
  // windows/linux script download, handshake).
  'connect-wizard': 'Connect Wizard',
  // Compliance Agents — `/agents/...` (enrollment, installer downloads,
  // results push, revoke, scan-now-push).
  agents: 'Compliance Agents',
};

const SUBMODULE_LABELS: Record<string, string> = {
  // ERM
  risks: 'Risks',
  kris: 'KRIs',
  incidents: 'Incidents',
  'mitigation-actions': 'Mitigation Actions',
  'internal-controls': 'Internal Controls',
  reviews: 'Reviews',
  appetite: 'Risk Appetite',
  rcsa: 'RCSA',
  'risk-assessments': 'Risk Assessments',
  'framework-risk-assessments': 'Framework Risk Assessments',
  scales: 'Scoring Scales',
  dependencies: 'Risk Dependencies',
  // Governance
  documents: 'Documents',
  'gap-analysis': 'Gap Analysis',
  attestations: 'Attestations',
  'attestation-campaigns': 'Attestation Campaigns',
  committees: 'Committees',
  'regulatory-changes': 'Regulatory Changes',
  'regulatory-feeds': 'Regulatory Feeds',
  workflows: 'Workflows',
  'workflow-templates': 'Workflow Templates',
  mappings: 'Mappings',
  exceptions: 'Exceptions',
  applicability: 'Applicability',
  versions: 'Document Versions',
  // Compliance
  policies: 'Policies',
  statements: 'Policy Statements',
  assessments: 'Assessments',
  // Evidence
  'cross-links': 'Cross-Module Links',
  'audit-packages': 'Audit Packages',
  // Vulnerability
  vulnerabilities: 'Findings',
  sla: 'SLA Config',
  departments: 'Departments',
  // Vendor risk
  vendors: 'Vendors',
  questionnaires: 'Questionnaires',
  'questionnaire-templates': 'Questionnaire Templates',
  // Admin
  users: 'Users',
  roles: 'Roles',
  permissions: 'Permissions',
  organization: 'Organization',
  'audit-logs': 'Audit Logs',
  // AI / cross-cutting
  ai: 'AI Assistant',
  // Workflow engine
  definitions: 'Definitions',
  instances: 'Instances',
  notifications: 'Notifications',
  'escalation-configs': 'Escalation Configs',
  // Frameworks
  parser: 'Parser',
  controls: 'Controls',
  alignment: 'Alignment',
  // Issue Management (URL: /issue-management/{issues|actions|comments|links|...})
  issues: 'Issues',
  actions: 'CAPA Actions',
  comments: 'Comments',
  links: 'Linked Items',
  matrices: 'Severity & Classification Matrices',
  'automation-flags': 'Automation Flags',
  'by-source': 'By Source',
  'from-source': 'Auto-Create from Source',
  // Criticality Assessments
  'info-system': 'Information System Assessments',
  'infra-asset': 'Infrastructure Asset Assessments',
  'by-asset': 'By Asset',
  coverage: 'Coverage Stats',
  // CIS Compliance Plugins (URL: /compliance-plugins/{runs|benchmarks|ingest|...})
  runs: 'Plugin Runs',
  benchmarks: 'Benchmarks',
  ingest: 'CIS PDF Ingest',
  'benchmark-mappings': 'Benchmark Mappings',
  'library-tree': 'Library Tree',
  'os-registry': 'OS Registry',
  'match-preview': 'Match Preview',
  'normalise-os': 'OS Normalisation',
  'classify-stream': 'Classification Stream',
  'classification-stats': 'Classification Stats',
  'review-queue': 'Review Queue',
  'review-bulk': 'Bulk Review',
  'scan-all': 'Scan-All',
  'per-asset-coverage': 'Per-Asset Coverage',
  'per-user-summary': 'Per-User Summary',
  'assets-overview': 'Assets Overview',
  'import-json': 'Import JSON',
  // Plugin-level paths nested under /compliance-plugins/{id}/{action}
  'control-mappings': 'Plugin Control Mappings',
  'asset-scope': 'Plugin Asset Scope',
  schedule: 'Plugin Schedule',
  // Compliance Agents (URL: /agents/{enroll|heartbeat|results|installer.*|...})
  enroll: 'Agent Enrollment',
  heartbeat: 'Agent Heartbeat',
  results: 'Agent Results',
  jobs: 'Agent Jobs Poll',
  revoke: 'Agent Revoke',
  'bulk-enroll': 'Bulk Enrollment',
  'fetch-creds': 'Collector Credentials Fetch',
  'scan-now-push': 'Scan-Now Push',
  // Per-OS installer download endpoints
  'installer.cmd': 'Windows Installer Download',
  'installer.sh': 'Linux Installer Download',
  'installer.command': 'macOS Installer Download',
  'installer.msi': 'Installer (MSI placeholder)',
  'installer.deb': 'Installer (DEB placeholder)',
  'installer.rpm': 'Installer (RPM placeholder)',
  'installer.pkg': 'Installer (PKG placeholder)',
  // Connect Wizard (URL: /connect-wizard/{issue-token|status|windows|linux|handshake})
  'issue-token': 'Issue Wizard Token',
  status: 'Wizard Status Poll',
  windows: 'Wizard Windows Script',
  linux: 'Wizard Linux Script',
  handshake: 'Wizard Handshake',
  // Connections under compliance-plugins
  connections: 'Connections',
  'connections-scope': 'Connection Scope',
};

const SUB_ENTITY_MODULES = new Set([
  'erm', 'evidence-mgmt', 'vuln-management',
  'control-library', 'governance', 'compliance', 'vendor-risk',
  'workflow-engine', 'framework-upload', 'auditor-portal',
  // Phase-2 additions — both surfaces nest resources under module prefix.
  'issue-management', 'criticality-assessments',
  // CIS additions — all three modules nest resources under the
  // top-level URL prefix (e.g. /compliance-plugins/runs/...).
  'compliance-plugins', 'connect-wizard', 'agents',
]);

function titleCase(s: string): string {
  return s
    .replace(/[-_]/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function deriveModuleContext(log: AuditLogEntry): { module: string; submodule: string | null } {
  const path = log.path || '';
  const normalized = path.replace(/^\/grc/, '').replace(/^\//, '');
  const parts = normalized.split('/').filter(Boolean);
  if (parts.length === 0) {
    const fallback = log.resource_type ? MODULE_LABELS[log.resource_type] || titleCase(log.resource_type) : 'System';
    return { module: fallback, submodule: null };
  }
  const moduleKey = parts[0];
  const moduleLabel = MODULE_LABELS[moduleKey] || titleCase(moduleKey);
  let submodule: string | null = null;
  // Sub-module = second segment when it isn't a numeric id, but only for
  // modules whose URL structure actually nests resources (most do).
  if (SUB_ENTITY_MODULES.has(moduleKey) && parts.length > 1 && !/^\d+$/.test(parts[1])) {
    const subKey = parts[1];
    submodule = SUBMODULE_LABELS[subKey] || titleCase(subKey);
  }
  // Avoid showing the same label twice (e.g. module=Documents, sub=Documents).
  if (submodule && submodule.toLowerCase() === moduleLabel.toLowerCase()) {
    submodule = null;
  }
  return { module: moduleLabel, submodule };
}

/**
 * Append module / sub-module context to the backend's description if it
 * doesn't already mention them, so each row reads as a self-contained
 * sentence ("Updated risk #5 — in Risks & ERM"). We only append when the
 * description doesn't already reference the module (e.g. for actions like
 * "Ran gap analysis on document #3 against framework "ISO 27001"" the
 * extra "in Governance" hint would be noise).
 */
function enrichDescription(log: AuditLogEntry): string {
  const base = log.description || `${titleCase(log.action || 'action')} on ${log.resource_type || 'record'}`;
  const ctx = deriveModuleContext(log);
  const moduleLabel = ctx.submodule || ctx.module;
  if (!moduleLabel || moduleLabel === 'System') return base;
  const lower = base.toLowerCase();
  if (lower.includes(moduleLabel.toLowerCase())) return base;
  // Some backend phrasings already say "in <module>" — don't double up.
  if (/\bin\s+\w/.test(lower) && (lower.includes('module') || lower.includes('framework') || lower.includes('document'))) {
    return base;
  }
  return `${base} — in ${moduleLabel}`;
}

function DetailRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex gap-3 py-1.5 border-b border-slate-100 last:border-0">
      <span className="w-36 shrink-0 text-xs font-medium text-slate-500 uppercase tracking-wide pt-0.5">{label}</span>
      <span className="text-sm text-slate-900 break-all">{value}</span>
    </div>
  );
}

// ── Page ─────────────────────────────────────────────────────────────────────

export default function AuditLogsPage() {
  const [logs, setLogs] = useState<AuditLogEntry[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [page, setPage] = useState(0);
  const [actionFilter, setActionFilter] = useState('all');
  const [moduleFilter, setModuleFilter] = useState('all');
  const [dateFilter, setDateFilter] = useState('all');
  const [availableActions, setAvailableActions] = useState<string[]>([]);
  const [availableModules, setAvailableModules] = useState<string[]>([]);
  const [selectedLog, setSelectedLog] = useState<AuditLogEntry | null>(null);
  const [aiSummary, setAiSummary] = useState<string | null>(null);
  const [aiSummaryLoading, setAiSummaryLoading] = useState(false);
  const limit = 50;

  useEffect(() => { fetchFilters(); }, []);
  useEffect(() => { fetchLogs(); }, [page, actionFilter, moduleFilter, dateFilter]);

  // v2 audit-AI: when the user opens a row, lazily fetch the AI summary
  // (cached server-side after first generation). Patches the row in the list
  // so subsequent opens are instant.
  useEffect(() => {
    if (!selectedLog) { setAiSummary(null); setAiSummaryLoading(false); return; }
    if (selectedLog.ai_summary) { setAiSummary(selectedLog.ai_summary); return; }
    let cancelled = false;
    setAiSummary(null);
    setAiSummaryLoading(true);
    adminApi.generateAuditLogAiSummary(selectedLog.id).then((resp) => {
      if (cancelled) return;
      const s = resp.data?.ai_summary || null;
      setAiSummary(s);
      if (s) setLogs((prev) => prev.map((l) => l.id === selectedLog.id ? { ...l, ai_summary: s } : l));
    }).catch(() => { if (!cancelled) setAiSummary(null); })
      .finally(() => { if (!cancelled) setAiSummaryLoading(false); });
    return () => { cancelled = true; };
  }, [selectedLog]);

  const getDateRange = () => {
    if (dateFilter === 'all') return {};
    const now = new Date();
    const toDate = now.toISOString().slice(0, 10);
    if (dateFilter === 'today') return { start_date: toDate, end_date: toDate };
    if (dateFilter === 'last_7_days') {
      const from = new Date(now); from.setDate(now.getDate() - 6);
      return { start_date: from.toISOString().slice(0, 10), end_date: toDate };
    }
    if (dateFilter === 'last_30_days') {
      const from = new Date(now); from.setDate(now.getDate() - 29);
      return { start_date: from.toISOString().slice(0, 10), end_date: toDate };
    }
    if (dateFilter === 'last_90_days') {
      const from = new Date(now); from.setDate(now.getDate() - 89);
      return { start_date: from.toISOString().slice(0, 10), end_date: toDate };
    }
    if (dateFilter === 'year_to_date') {
      const from = new Date(now.getFullYear(), 0, 1);
      return { start_date: from.toISOString().slice(0, 10), end_date: toDate };
    }
    if (dateFilter === 'last_year') {
      const from = new Date(now); from.setFullYear(now.getFullYear() - 1);
      return { start_date: from.toISOString().slice(0, 10), end_date: toDate };
    }
    return {};
  };

  const fetchFilters = async () => {
    try {
      const res = await adminApi.getAuditLogFilters();
      setAvailableActions(res.data.actions || []);
      setAvailableModules(res.data.modules || []);
    } catch {
      setAvailableActions([]);
      setAvailableModules([]);
    }
  };

  const fetchLogs = async () => {
    try {
      setLoading(true);
      const dr = getDateRange();
      const res = await adminApi.getAuditLogs({
        limit,
        offset: page * limit,
        action: actionFilter !== 'all' ? actionFilter : undefined,
        module: moduleFilter !== 'all' ? moduleFilter : undefined,
        start_date: (dr as Record<string, string>).start_date,
        end_date: (dr as Record<string, string>).end_date,
      });
      setLogs(res.data.logs);
      setTotal(res.data.total);
    } catch (err: unknown) {
      const e = err as { response?: { data?: { detail?: string } } };
      setError(e.response?.data?.detail || 'Failed to load audit logs');
    } finally {
      setLoading(false);
    }
  };

  const handleSingleApply = (setter: (v: string) => void) => (values: string[]) => {
    setPage(0);
    setter(values[0] || 'all');
  };

  // ── Columns ──────────────────────────────────────────────────────────────

  const columns = [
    {
      id: 'timestamp',
      header: 'Timestamp',
      accessor: (log: AuditLogEntry) => {
        const { date, time } = fmtTs(log.timestamp);
        return (
          <div className="min-w-[110px]">
            <div className="text-xs font-medium text-slate-900">{date}</div>
            <div className="text-xs text-slate-500 mt-0.5">{time}</div>
          </div>
        );
      },
    },
    {
      id: 'user',
      header: 'User',
      accessor: (log: AuditLogEntry) => (
        <div className="flex items-center gap-2 min-w-[120px]">
          <UserAvatar name={log.user_name} />
          <span className="text-sm font-medium text-slate-900 truncate max-w-[140px]" title={log.user_name}>
            {log.user_name}
          </span>
        </div>
      ),
    },
    {
      id: 'action',
      header: 'Action',
      accessor: (log: AuditLogEntry) => <ActionBadge action={log.action} />,
    },
    {
      id: 'module',
      header: 'Module',
      accessor: (log: AuditLogEntry) => {
        const ctx = deriveModuleContext(log);
        return (
          <div className="min-w-[140px] max-w-[180px]">
            <div className="text-sm font-medium text-slate-900 truncate" title={ctx.module}>
              {ctx.module}
            </div>
            {ctx.submodule && (
              <div className="text-xs text-slate-500 truncate" title={ctx.submodule}>
                {ctx.submodule}
              </div>
            )}
          </div>
        );
      },
    },
    {
      id: 'activity',
      header: 'Activity',
      accessor: (log: AuditLogEntry) => (
        <span className="text-sm text-slate-900">
          {enrichDescription(log)}
        </span>
      ),
    },
    {
      id: 'details',
      header: '',
      accessor: (log: AuditLogEntry) => (
        <button
          type="button"
          onClick={() => setSelectedLog(log)}
          className="rounded border border-primary-200 bg-primary-50 px-2.5 py-1 text-xs font-medium text-primary-700 hover:bg-primary-100 whitespace-nowrap"
        >
          View Details
        </button>
      ),
    },
  ];

  // ── Detail Modal ─────────────────────────────────────────────────────────

  const modal = selectedLog && (() => {
    const { date, time } = fmtTs(selectedLog.timestamp);
    const req = (selectedLog.details?.request as Record<string, unknown> | null) ?? {};
    const hasPayload = req && Object.keys(req).length > 0;
    const statusCode = selectedLog.status_code ?? 0;

    return (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
        onClick={() => setSelectedLog(null)}
      >
        <div
          className="w-full max-w-2xl max-h-[90vh] overflow-hidden rounded-xl bg-white shadow-xl flex flex-col"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4">
            <div className="flex items-center gap-3">
              <ActionBadge action={selectedLog.action} />
              <h3 className="text-sm font-semibold text-slate-900">{selectedLog.description || 'Audit Log Details'}</h3>
            </div>
            <button
              type="button"
              onClick={() => setSelectedLog(null)}
              className="rounded p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-900"
              aria-label="Close"
            >
              <svg className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
              </svg>
            </button>
          </div>

          {/* Body */}
          <div className="overflow-auto p-5 space-y-5">
            {/* v2 audit-AI: human-readable summary lazily generated by the
                backend and cached on the row. Falls back gracefully when
                the AI is unavailable or returns nothing. */}
            <section>
              <p className="text-xs font-semibold text-primary-700 uppercase tracking-widest mb-2">What happened</p>
              <div className="bg-primary-50 border border-primary-100 rounded-lg px-4 py-3 min-h-[44px]">
                {aiSummaryLoading ? (
                  <p className="text-xs font-medium text-primary-700 inline-flex items-center gap-2">
                    <svg className="h-3 w-3 animate-spin" viewBox="0 0 24 24" fill="none">
                      <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" className="opacity-25" />
                      <path d="M12 2a10 10 0 0 1 10 10" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
                    </svg>
                    Generating readable summary…
                  </p>
                ) : aiSummary ? (
                  <div className="prose prose-sm max-w-none prose-headings:font-semibold prose-headings:text-slate-800 prose-p:text-slate-700 prose-li:text-slate-700 prose-strong:text-slate-900 prose-ul:my-1 prose-ol:my-1 prose-li:my-0">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{aiSummary}</ReactMarkdown>
                  </div>
                ) : (
                  <p className="text-xs text-slate-500">{enrichDescription(selectedLog)}</p>
                )}
              </div>
            </section>

            {/* Who / When */}
            <section>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2">Overview</p>
              <div className="bg-slate-50 rounded-lg px-4 py-1 divide-y divide-slate-100">
                <DetailRow label="User" value={
                  <div className="flex items-center gap-2">
                    <UserAvatar name={selectedLog.user_name} />
                    <span>{selectedLog.user_name}</span>
                  </div>
                } />
                <DetailRow label="Timestamp" value={`${date} at ${time}`} />
                {selectedLog.ip_address && <DetailRow label="IP Address" value={selectedLog.ip_address} />}
              </div>
            </section>

            {/* Action / Resource */}
            <section>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2">Action Details</p>
              <div className="bg-slate-50 rounded-lg px-4 py-1 divide-y divide-slate-100">
                <DetailRow label="Action" value={<ActionBadge action={selectedLog.action} />} />
                {(() => {
                  const ctx = deriveModuleContext(selectedLog);
                  return (
                    <>
                      <DetailRow label="Module" value={ctx.module || '—'} />
                      {ctx.submodule && <DetailRow label="Sub-module" value={ctx.submodule} />}
                    </>
                  );
                })()}
                <DetailRow
                  label="Resource Type"
                  value={
                    <span className="font-mono text-xs text-slate-500">
                      {selectedLog.resource_type || '—'}
                    </span>
                  }
                />
                {selectedLog.resource_id && <DetailRow label="Record ID" value={`#${selectedLog.resource_id}`} />}
              </div>
            </section>

            {/* Technical */}
            <section>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2">Request Info</p>
              <div className="bg-slate-50 rounded-lg px-4 py-1 divide-y divide-slate-100">
                {selectedLog.method && <DetailRow label="Method" value={selectedLog.method} />}
                {selectedLog.path && (
                  <DetailRow label="Path" value={
                    <span className="font-mono text-xs break-all">{selectedLog.path}</span>
                  } />
                )}
                {selectedLog.status_code && (
                  <DetailRow label="Status" value={
                    <span className={statusCode >= 400 ? 'text-rose-600 font-medium' : 'text-emerald-700 font-medium'}>
                      {selectedLog.status_code}
                    </span>
                  } />
                )}
                {selectedLog.duration_ms != null && (
                  <DetailRow label="Duration" value={`${selectedLog.duration_ms} ms`} />
                )}
                {Boolean(selectedLog.details?.user_agent) && (
                  <DetailRow label="User Agent" value={
                    <span className="text-xs text-slate-500 break-all">{String(selectedLog.details.user_agent)}</span>
                  } />
                )}
              </div>
            </section>

            {/* Payload */}
            {hasPayload && (
              <section>
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-widest mb-2">Request Payload</p>
                <pre className="text-xs bg-slate-50 border border-slate-200 rounded-lg p-3 text-slate-900 whitespace-pre-wrap break-words max-h-60 overflow-auto">
                  {JSON.stringify(req, null, 2)}
                </pre>
              </section>
            )}
          </div>

          {/* Footer */}
          <div className="flex justify-end border-t border-slate-200 px-5 py-3">
            <button
              type="button"
              onClick={() => setSelectedLog(null)}
              className="rounded-lg bg-slate-100 px-4 py-2 text-sm text-slate-700 hover:bg-slate-200"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    );
  })();

  // ── Render ────────────────────────────────────────────────────────────────

  if (loading && logs.length === 0) {
    return <PageLoader className="h-64" />;
  }

  const actionItems  = availableActions.map((a) => ({ value: a, label: ACTION_CFG[a]?.label ?? a }));
  const moduleItems  = availableModules.map((m) => ({ value: m, label: m }));
  const dateItems    = [
    { value: 'today',         label: 'Today' },
    { value: 'last_7_days',   label: 'Last 7 days' },
    { value: 'last_30_days',  label: 'Last 30 days' },
    { value: 'last_90_days',  label: 'Last 90 days' },
    { value: 'year_to_date',  label: 'Year to date' },
    { value: 'last_year',     label: 'Last 12 months' },
    // 'all' is handled by the Clear-filters button + the trigger label
    // showing "All time" when nothing is picked.
  ];

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Title */}
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div className="min-w-0">
          <h1 className="text-lg sm:text-xl font-semibold text-slate-900 tracking-tight">Audit Logs</h1>
          <p className="mt-1 text-sm text-slate-600">Track every action taken by users across the platform</p>
        </div>
        {total > 0 && (
          <span className="text-xs text-slate-500 self-center">{total.toLocaleString()} total records</span>
        )}
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-2">
        <MultiSelectDropdown
          title="Action"
          items={actionItems}
          selectedValues={actionFilter !== 'all' ? [actionFilter] : []}
          onApply={handleSingleApply(setActionFilter)}
          multiSelect={false}
          autoApply
          placeholder="All Actions"
          size="md"
        />
        <MultiSelectDropdown
          title="Module"
          items={moduleItems}
          selectedValues={moduleFilter !== 'all' ? [moduleFilter] : []}
          onApply={handleSingleApply(setModuleFilter)}
          multiSelect={false}
          autoApply
          placeholder="All Modules"
          size="md"
        />
        <MultiSelectDropdown
          title="Date"
          items={dateItems}
          selectedValues={dateFilter !== 'all' ? [dateFilter] : []}
          onApply={handleSingleApply(setDateFilter)}
          multiSelect={false}
          autoApply
          placeholder="All Dates"
          size="md"
        />
        {(actionFilter !== 'all' || moduleFilter !== 'all' || dateFilter !== 'all') && (
          <button
            type="button"
            onClick={() => { setActionFilter('all'); setModuleFilter('all'); setDateFilter('all'); setPage(0); }}
            className="text-xs text-slate-500 hover:text-slate-900 underline"
          >
            Clear filters
          </button>
        )}
      </div>

      {error && (
        <div className="bg-rose-50 border border-rose-200 rounded-lg p-4 text-sm text-rose-700 flex justify-between">
          <span>{error}</span>
          <button onClick={() => setError(null)} className="underline ml-4 shrink-0">Dismiss</button>
        </div>
      )}

      {/* Table */}
      <div className="bg-white border border-slate-200 rounded-lg overflow-hidden">
        <DataTable data={logs} columns={columns} />
        {loading && logs.length > 0 && (
          <div className="flex justify-center py-3 border-t border-slate-100">
            <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-primary-400" />
          </div>
        )}
      </div>

      {/* Pagination — operators reading audit history need to see WHICH
          page they're on and TOTAL pages, not just Prev/Next. Without
          this they'd think the history ends at page 4 (or whatever).
          We surface first / last jumps too so they can leap to the
          oldest entries instantly. */}
      {total > limit && (() => {
        const totalPages = Math.ceil(total / limit);
        const currentPage = page + 1;  // 1-indexed for display
        return (
          <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-200 bg-white px-4 py-3">
            <div className="text-sm text-slate-700">
              <strong className="text-slate-900">{page * limit + 1}–{Math.min((page + 1) * limit, total)}</strong>
              <span className="text-slate-500"> of </span>
              <strong className="text-slate-900">{total.toLocaleString()}</strong>
              <span className="text-slate-500"> rows · page </span>
              <strong className="text-slate-900">{currentPage}</strong>
              <span className="text-slate-500"> of </span>
              <strong className="text-slate-900">{totalPages.toLocaleString()}</strong>
            </div>
            <div className="flex gap-1.5">
              <button
                onClick={() => setPage(0)}
                disabled={page === 0}
                title="Jump to newest"
                className="px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded text-xs font-medium disabled:opacity-40 disabled:cursor-not-allowed"
              >
                « First
              </button>
              <button
                onClick={() => setPage((p) => Math.max(0, p - 1))}
                disabled={page === 0}
                className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded text-xs font-medium disabled:opacity-40 disabled:cursor-not-allowed"
              >
                ‹ Prev
              </button>
              <button
                onClick={() => setPage((p) => p + 1)}
                disabled={(page + 1) * limit >= total}
                className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded text-xs font-medium disabled:opacity-40 disabled:cursor-not-allowed"
              >
                Next ›
              </button>
              <button
                onClick={() => setPage(totalPages - 1)}
                disabled={(page + 1) * limit >= total}
                title="Jump to oldest (tenant-creation era)"
                className="px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded text-xs font-medium disabled:opacity-40 disabled:cursor-not-allowed"
              >
                Last »
              </button>
            </div>
          </div>
        );
      })()}

      {modal}
    </div>
  );
}
